/*
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
 * Autogenerated by Loqui.  Do not manually change.
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
*/
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Loqui;
using Noggog;
using Noggog.Notifying;
using Mutagen.Bethesda.Oblivion.Internals;
using Mutagen.Bethesda.Oblivion;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Internals;
using System.Xml;
using System.Xml.Linq;
using System.IO;
using Noggog.Xml;
using Loqui.Xml;
using System.Diagnostics;
using Mutagen.Bethesda.Binary;

namespace Mutagen.Bethesda.Oblivion
{
    #region Class
    public partial class Spell : NamedMajorRecord, ISpell, ILoquiObjectSetter, IEquatable<Spell>
    {
        ILoquiRegistration ILoquiObject.Registration => Spell_Registration.Instance;
        public new static Spell_Registration Registration => Spell_Registration.Instance;

        #region Ctor
        public Spell()
        {
            CustomCtor();
        }
        partial void CustomCtor();
        #endregion

        #region Type
        protected readonly INotifyingSetItem<Spell.SpellType> _Type = NotifyingSetItem.Factory<Spell.SpellType>(markAsSet: false);
        public INotifyingSetItem<Spell.SpellType> Type_Property => _Type;
        public Spell.SpellType Type
        {
            get => this._Type.Item;
            set => this._Type.Set(value);
        }
        INotifyingSetItem<Spell.SpellType> ISpell.Type_Property => this.Type_Property;
        INotifyingSetItemGetter<Spell.SpellType> ISpellGetter.Type_Property => this.Type_Property;
        #endregion
        #region Cost
        protected readonly INotifyingSetItem<UInt32> _Cost = NotifyingSetItem.Factory<UInt32>(markAsSet: false);
        public INotifyingSetItem<UInt32> Cost_Property => _Cost;
        public UInt32 Cost
        {
            get => this._Cost.Item;
            set => this._Cost.Set(value);
        }
        INotifyingSetItem<UInt32> ISpell.Cost_Property => this.Cost_Property;
        INotifyingSetItemGetter<UInt32> ISpellGetter.Cost_Property => this.Cost_Property;
        #endregion
        #region Level
        protected readonly INotifyingSetItem<Spell.SpellLevel> _Level = NotifyingSetItem.Factory<Spell.SpellLevel>(markAsSet: false);
        public INotifyingSetItem<Spell.SpellLevel> Level_Property => _Level;
        public Spell.SpellLevel Level
        {
            get => this._Level.Item;
            set => this._Level.Set(value);
        }
        INotifyingSetItem<Spell.SpellLevel> ISpell.Level_Property => this.Level_Property;
        INotifyingSetItemGetter<Spell.SpellLevel> ISpellGetter.Level_Property => this.Level_Property;
        #endregion
        #region Flag
        protected readonly INotifyingSetItem<Spell.SpellFlag> _Flag = NotifyingSetItem.Factory<Spell.SpellFlag>(markAsSet: false);
        public INotifyingSetItem<Spell.SpellFlag> Flag_Property => _Flag;
        public Spell.SpellFlag Flag
        {
            get => this._Flag.Item;
            set => this._Flag.Set(value);
        }
        INotifyingSetItem<Spell.SpellFlag> ISpell.Flag_Property => this.Flag_Property;
        INotifyingSetItemGetter<Spell.SpellFlag> ISpellGetter.Flag_Property => this.Flag_Property;
        #endregion
        #region Effects
        private readonly INotifyingList<Effect> _Effects = new NotifyingList<Effect>();
        public INotifyingList<Effect> Effects => _Effects;
        #region Interface Members
        INotifyingList<Effect> ISpell.Effects => _Effects;
        INotifyingListGetter<Effect> ISpellGetter.Effects => _Effects;
        #endregion

        #endregion

        #region Loqui Getter Interface

        protected override object GetNthObject(ushort index) => SpellCommon.GetNthObject(index, this);

        protected override bool GetNthObjectHasBeenSet(ushort index) => SpellCommon.GetNthObjectHasBeenSet(index, this);

        protected override void UnsetNthObject(ushort index, NotifyingUnsetParameters? cmds) => SpellCommon.UnsetNthObject(index, this, cmds);

        #endregion

        #region Loqui Interface
        protected override void SetNthObjectHasBeenSet(ushort index, bool on)
        {
            SpellCommon.SetNthObjectHasBeenSet(index, on, this);
        }

        #endregion

        #region To String
        public override string ToString()
        {
            return SpellCommon.ToString(this, printMask: null);
        }

        public string ToString(
            string name = null,
            Spell_Mask<bool> printMask = null)
        {
            return SpellCommon.ToString(this, name: name, printMask: printMask);
        }

        public override void ToString(
            FileGeneration fg,
            string name = null)
        {
            SpellCommon.ToString(this, fg, name: name, printMask: null);
        }

        #endregion

        public new Spell_Mask<bool> GetHasBeenSetMask()
        {
            return SpellCommon.GetHasBeenSetMask(this);
        }
        #region Equals and Hash
        public override bool Equals(object obj)
        {
            if (!(obj is Spell rhs)) return false;
            return Equals(rhs);
        }

        public bool Equals(Spell rhs)
        {
            if (rhs == null) return false;
            if (!base.Equals(rhs)) return false;
            if (Type_Property.HasBeenSet != rhs.Type_Property.HasBeenSet) return false;
            if (Type_Property.HasBeenSet)
            {
                if (Type != rhs.Type) return false;
            }
            if (Cost_Property.HasBeenSet != rhs.Cost_Property.HasBeenSet) return false;
            if (Cost_Property.HasBeenSet)
            {
                if (Cost != rhs.Cost) return false;
            }
            if (Level_Property.HasBeenSet != rhs.Level_Property.HasBeenSet) return false;
            if (Level_Property.HasBeenSet)
            {
                if (Level != rhs.Level) return false;
            }
            if (Flag_Property.HasBeenSet != rhs.Flag_Property.HasBeenSet) return false;
            if (Flag_Property.HasBeenSet)
            {
                if (Flag != rhs.Flag) return false;
            }
            if (Effects.HasBeenSet != rhs.Effects.HasBeenSet) return false;
            if (Effects.HasBeenSet)
            {
                if (!Effects.SequenceEqual(rhs.Effects)) return false;
            }
            return true;
        }

        public override int GetHashCode()
        {
            int ret = 0;
            if (Type_Property.HasBeenSet)
            {
                ret = HashHelper.GetHashCode(Type).CombineHashCode(ret);
            }
            if (Cost_Property.HasBeenSet)
            {
                ret = HashHelper.GetHashCode(Cost).CombineHashCode(ret);
            }
            if (Level_Property.HasBeenSet)
            {
                ret = HashHelper.GetHashCode(Level).CombineHashCode(ret);
            }
            if (Flag_Property.HasBeenSet)
            {
                ret = HashHelper.GetHashCode(Flag).CombineHashCode(ret);
            }
            if (Effects.HasBeenSet)
            {
                ret = HashHelper.GetHashCode(Effects).CombineHashCode(ret);
            }
            ret = ret.CombineHashCode(base.GetHashCode());
            return ret;
        }

        #endregion


        #region XML Translation
        #region XML Create
        [DebuggerStepThrough]
        public new static Spell Create_XML(XElement root)
        {
            return Create_XML(
                root: root,
                doMasks: false,
                errorMask: out var errorMask);
        }

        [DebuggerStepThrough]
        public static Spell Create_XML(
            XElement root,
            out Spell_ErrorMask errorMask)
        {
            return Create_XML(
                root: root,
                doMasks: true,
                errorMask: out errorMask);
        }

        [DebuggerStepThrough]
        public static Spell Create_XML(
            XElement root,
            bool doMasks,
            out Spell_ErrorMask errorMask)
        {
            var ret = Create_XML(
                root: root,
                doMasks: doMasks);
            errorMask = ret.ErrorMask;
            return ret.Object;
        }

        [DebuggerStepThrough]
        public static (Spell Object, Spell_ErrorMask ErrorMask) Create_XML(
            XElement root,
            bool doMasks)
        {
            Spell_ErrorMask errMaskRet = null;
            var ret = Create_XML_Internal(
                root: root,
                errorMask: doMasks ? () => errMaskRet ?? (errMaskRet = new Spell_ErrorMask()) : default(Func<Spell_ErrorMask>));
            return (ret, errMaskRet);
        }

        public static Spell Create_XML(string path)
        {
            var root = XDocument.Load(path).Root;
            return Create_XML(root: root);
        }

        public static Spell Create_XML(
            string path,
            out Spell_ErrorMask errorMask)
        {
            var root = XDocument.Load(path).Root;
            return Create_XML(
                root: root,
                errorMask: out errorMask);
        }

        public static Spell Create_XML(Stream stream)
        {
            var root = XDocument.Load(stream).Root;
            return Create_XML(root: root);
        }

        public static Spell Create_XML(
            Stream stream,
            out Spell_ErrorMask errorMask)
        {
            var root = XDocument.Load(stream).Root;
            return Create_XML(
                root: root,
                errorMask: out errorMask);
        }

        #endregion

        #region XML Copy In
        public override void CopyIn_XML(
            XElement root,
            NotifyingFireParameters? cmds = null)
        {
            LoquiXmlTranslation<Spell, Spell_ErrorMask>.Instance.CopyIn(
                root: root,
                item: this,
                skipProtected: true,
                doMasks: false,
                mask: out var errorMask,
                cmds: cmds);
        }

        public virtual void CopyIn_XML(
            XElement root,
            out Spell_ErrorMask errorMask,
            NotifyingFireParameters? cmds = null)
        {
            LoquiXmlTranslation<Spell, Spell_ErrorMask>.Instance.CopyIn(
                root: root,
                item: this,
                skipProtected: true,
                doMasks: true,
                mask: out errorMask,
                cmds: cmds);
        }

        public void CopyIn_XML(
            string path,
            NotifyingFireParameters? cmds = null)
        {
            var root = XDocument.Load(path).Root;
            this.CopyIn_XML(
                root: root,
                cmds: cmds);
        }

        public void CopyIn_XML(
            string path,
            out Spell_ErrorMask errorMask,
            NotifyingFireParameters? cmds = null)
        {
            var root = XDocument.Load(path).Root;
            this.CopyIn_XML(
                root: root,
                errorMask: out errorMask,
                cmds: cmds);
        }

        public void CopyIn_XML(
            Stream stream,
            NotifyingFireParameters? cmds = null)
        {
            var root = XDocument.Load(stream).Root;
            this.CopyIn_XML(
                root: root,
                cmds: cmds);
        }

        public void CopyIn_XML(
            Stream stream,
            out Spell_ErrorMask errorMask,
            NotifyingFireParameters? cmds = null)
        {
            var root = XDocument.Load(stream).Root;
            this.CopyIn_XML(
                root: root,
                errorMask: out errorMask,
                cmds: cmds);
        }

        public override void CopyIn_XML(
            XElement root,
            out NamedMajorRecord_ErrorMask errorMask,
            NotifyingFireParameters? cmds = null)
        {
            this.CopyIn_XML(
                root: root,
                errorMask: out Spell_ErrorMask errMask,
                cmds: cmds);
            errorMask = errMask;
        }

        public override void CopyIn_XML(
            XElement root,
            out MajorRecord_ErrorMask errorMask,
            NotifyingFireParameters? cmds = null)
        {
            this.CopyIn_XML(
                root: root,
                errorMask: out Spell_ErrorMask errMask,
                cmds: cmds);
            errorMask = errMask;
        }

        #endregion

        #region XML Write
        public virtual void Write_XML(
            XmlWriter writer,
            out Spell_ErrorMask errorMask,
            string name = null)
        {
            errorMask = (Spell_ErrorMask)this.Write_XML_Internal(
                writer: writer,
                name: name,
                doMasks: true);
        }

        public virtual void Write_XML(
            string path,
            out Spell_ErrorMask errorMask,
            string name = null)
        {
            using (var writer = new XmlTextWriter(path, Encoding.ASCII))
            {
                writer.Formatting = Formatting.Indented;
                writer.Indentation = 3;
                Write_XML(
                    writer: writer,
                    name: name,
                    errorMask: out errorMask);
            }
        }

        public virtual void Write_XML(
            Stream stream,
            out Spell_ErrorMask errorMask,
            string name = null)
        {
            using (var writer = new XmlTextWriter(stream, Encoding.ASCII))
            {
                writer.Formatting = Formatting.Indented;
                writer.Indentation = 3;
                Write_XML(
                    writer: writer,
                    name: name,
                    errorMask: out errorMask);
            }
        }

        public override void Write_XML(
            XmlWriter writer,
            string name = null)
        {
            this.Write_XML_Internal(
                writer: writer,
                name: name,
                doMasks: false);
        }

        public override void Write_XML(
            string path,
            string name = null)
        {
            using (var writer = new XmlTextWriter(path, Encoding.ASCII))
            {
                writer.Formatting = Formatting.Indented;
                writer.Indentation = 3;
                Write_XML(
                    writer: writer,
                    name: name);
            }
        }

        public override void Write_XML(
            Stream stream,
            string name = null)
        {
            using (var writer = new XmlTextWriter(stream, Encoding.ASCII))
            {
                writer.Formatting = Formatting.Indented;
                writer.Indentation = 3;
                Write_XML(
                    writer: writer,
                    name: name);
            }
        }

        protected override object Write_XML_Internal(
            XmlWriter writer,
            bool doMasks,
            string name = null)
        {
            SpellCommon.Write_XML(
                writer: writer,
                item: this,
                doMasks: doMasks,
                errorMask: out var errorMask);
            return errorMask;
        }
        #endregion

        private static Spell Create_XML_Internal(
            XElement root,
            Func<Spell_ErrorMask> errorMask)
        {
            var ret = new Spell();
            try
            {
                foreach (var elem in root.Elements())
                {
                    Fill_XML_Internal(
                        item: ret,
                        root: elem,
                        name: elem.Name.LocalName,
                        errorMask: errorMask);
                }
            }
            catch (Exception ex)
            when (errorMask != null)
            {
                errorMask().Overall = ex;
            }
            return ret;
        }

        protected static void Fill_XML_Internal(
            Spell item,
            XElement root,
            string name,
            Func<Spell_ErrorMask> errorMask)
        {
            switch (name)
            {
                case "Type":
                    item._Type.SetIfSucceeded(EnumXmlTranslation<Spell.SpellType>.Instance.Parse(
                        root,
                        nullable: false,
                        fieldIndex: (int)Spell_FieldIndex.Type,
                        errorMask: errorMask).Bubble((o) => o.Value));
                    break;
                case "Cost":
                    item._Cost.SetIfSucceeded(UInt32XmlTranslation.Instance.ParseNonNull(
                        root,
                        fieldIndex: (int)Spell_FieldIndex.Cost,
                        errorMask: errorMask));
                    break;
                case "Level":
                    item._Level.SetIfSucceeded(EnumXmlTranslation<Spell.SpellLevel>.Instance.Parse(
                        root,
                        nullable: false,
                        fieldIndex: (int)Spell_FieldIndex.Level,
                        errorMask: errorMask).Bubble((o) => o.Value));
                    break;
                case "Flag":
                    item._Flag.SetIfSucceeded(EnumXmlTranslation<Spell.SpellFlag>.Instance.Parse(
                        root,
                        nullable: false,
                        fieldIndex: (int)Spell_FieldIndex.Flag,
                        errorMask: errorMask).Bubble((o) => o.Value));
                    break;
                case "Effects":
                    item._Effects.SetIfSucceeded(ListXmlTranslation<Effect, MaskItem<Exception, Effect_ErrorMask>>.Instance.Parse(
                        root: root,
                        fieldIndex: (int)Spell_FieldIndex.Effects,
                        errorMask: errorMask,
                        transl: (XElement r, bool listDoMasks, out MaskItem<Exception, Effect_ErrorMask> listSubMask) =>
                        {
                            return LoquiXmlTranslation<Effect, Effect_ErrorMask>.Instance.Parse(
                                root: r,
                                doMasks: listDoMasks,
                                errorMask: out listSubMask);
                        }
                        ));
                    break;
                default:
                    NamedMajorRecord.Fill_XML_Internal(
                        item: item,
                        root: root,
                        name: name,
                        errorMask: errorMask);
                    break;
            }
        }

        #endregion

        #region Binary Translation
        #region Binary Create
        [DebuggerStepThrough]
        public new static Spell Create_Binary(MutagenFrame frame)
        {
            return Create_Binary(
                frame: frame,
                doMasks: false,
                errorMask: out var errorMask);
        }

        [DebuggerStepThrough]
        public static Spell Create_Binary(
            MutagenFrame frame,
            out Spell_ErrorMask errorMask)
        {
            return Create_Binary(
                frame: frame,
                doMasks: true,
                errorMask: out errorMask);
        }

        [DebuggerStepThrough]
        public static Spell Create_Binary(
            MutagenFrame frame,
            bool doMasks,
            out Spell_ErrorMask errorMask)
        {
            var ret = Create_Binary(
                frame: frame,
                doMasks: doMasks);
            errorMask = ret.ErrorMask;
            return ret.Object;
        }

        [DebuggerStepThrough]
        public static (Spell Object, Spell_ErrorMask ErrorMask) Create_Binary(
            MutagenFrame frame,
            bool doMasks)
        {
            Spell_ErrorMask errMaskRet = null;
            var ret = Create_Binary_Internal(
                frame: frame,
                errorMask: doMasks ? () => errMaskRet ?? (errMaskRet = new Spell_ErrorMask()) : default(Func<Spell_ErrorMask>));
            return (ret, errMaskRet);
        }

        public static Spell Create_Binary(string path)
        {
            using (var reader = new MutagenReader(path))
            {
                var frame = new MutagenFrame(reader);
                return Create_Binary(frame: frame);
            }
        }

        public static Spell Create_Binary(
            string path,
            out Spell_ErrorMask errorMask)
        {
            using (var reader = new MutagenReader(path))
            {
                var frame = new MutagenFrame(reader);
                return Create_Binary(
                    frame: frame,
                    errorMask: out errorMask);
            }
        }

        public static Spell Create_Binary(Stream stream)
        {
            using (var reader = new MutagenReader(stream))
            {
                var frame = new MutagenFrame(reader);
                return Create_Binary(frame: frame);
            }
        }

        public static Spell Create_Binary(
            Stream stream,
            out Spell_ErrorMask errorMask)
        {
            using (var reader = new MutagenReader(stream))
            {
                var frame = new MutagenFrame(reader);
                return Create_Binary(
                    frame: frame,
                    errorMask: out errorMask);
            }
        }

        #endregion

        #region Binary Copy In
        public override void CopyIn_Binary(
            MutagenFrame frame,
            NotifyingFireParameters? cmds = null)
        {
            LoquiBinaryTranslation<Spell, Spell_ErrorMask>.Instance.CopyIn(
                frame: frame,
                item: this,
                skipProtected: true,
                doMasks: false,
                mask: out var errorMask,
                cmds: cmds);
        }

        public virtual void CopyIn_Binary(
            MutagenFrame frame,
            out Spell_ErrorMask errorMask,
            NotifyingFireParameters? cmds = null)
        {
            LoquiBinaryTranslation<Spell, Spell_ErrorMask>.Instance.CopyIn(
                frame: frame,
                item: this,
                skipProtected: true,
                doMasks: true,
                mask: out errorMask,
                cmds: cmds);
        }

        public void CopyIn_Binary(
            string path,
            NotifyingFireParameters? cmds = null)
        {
            using (var reader = new MutagenReader(path))
            {
                var frame = new MutagenFrame(reader);
                this.CopyIn_Binary(
                    frame: frame,
                    cmds: cmds);
            }
        }

        public void CopyIn_Binary(
            string path,
            out Spell_ErrorMask errorMask,
            NotifyingFireParameters? cmds = null)
        {
            using (var reader = new MutagenReader(path))
            {
                var frame = new MutagenFrame(reader);
                this.CopyIn_Binary(
                    frame: frame,
                    errorMask: out errorMask,
                    cmds: cmds);
            }
        }

        public void CopyIn_Binary(
            Stream stream,
            NotifyingFireParameters? cmds = null)
        {
            using (var reader = new MutagenReader(stream))
            {
                var frame = new MutagenFrame(reader);
                this.CopyIn_Binary(
                    frame: frame,
                    cmds: cmds);
            }
        }

        public void CopyIn_Binary(
            Stream stream,
            out Spell_ErrorMask errorMask,
            NotifyingFireParameters? cmds = null)
        {
            using (var reader = new MutagenReader(stream))
            {
                var frame = new MutagenFrame(reader);
                this.CopyIn_Binary(
                    frame: frame,
                    errorMask: out errorMask,
                    cmds: cmds);
            }
        }

        public override void CopyIn_Binary(
            MutagenFrame frame,
            out NamedMajorRecord_ErrorMask errorMask,
            NotifyingFireParameters? cmds = null)
        {
            this.CopyIn_Binary(
                frame: frame,
                errorMask: out Spell_ErrorMask errMask,
                cmds: cmds);
            errorMask = errMask;
        }

        public override void CopyIn_Binary(
            MutagenFrame frame,
            out MajorRecord_ErrorMask errorMask,
            NotifyingFireParameters? cmds = null)
        {
            this.CopyIn_Binary(
                frame: frame,
                errorMask: out Spell_ErrorMask errMask,
                cmds: cmds);
            errorMask = errMask;
        }

        #endregion

        #region Binary Write
        public virtual void Write_Binary(
            MutagenWriter writer,
            out Spell_ErrorMask errorMask)
        {
            errorMask = (Spell_ErrorMask)this.Write_Binary_Internal(
                writer: writer,
                doMasks: true);
        }

        public virtual void Write_Binary(
            string path,
            out Spell_ErrorMask errorMask)
        {
            using (var writer = new MutagenWriter(path))
            {
                Write_Binary(
                    writer: writer,
                    errorMask: out errorMask);
            }
        }

        public virtual void Write_Binary(
            Stream stream,
            out Spell_ErrorMask errorMask)
        {
            using (var writer = new MutagenWriter(stream))
            {
                Write_Binary(
                    writer: writer,
                    errorMask: out errorMask);
            }
        }

        public override void Write_Binary(MutagenWriter writer)
        {
            this.Write_Binary_Internal(
                writer: writer,
                doMasks: false);
        }

        public override void Write_Binary(string path)
        {
            using (var writer = new MutagenWriter(path))
            {
                Write_Binary(writer: writer);
            }
        }

        public override void Write_Binary(Stream stream)
        {
            using (var writer = new MutagenWriter(stream))
            {
                Write_Binary(writer: writer);
            }
        }

        protected override object Write_Binary_Internal(
            MutagenWriter writer,
            bool doMasks)
        {
            SpellCommon.Write_Binary(
                writer: writer,
                item: this,
                doMasks: doMasks,
                errorMask: out var errorMask);
            return errorMask;
        }
        #endregion

        private static Spell Create_Binary_Internal(
            MutagenFrame frame,
            Func<Spell_ErrorMask> errorMask)
        {
            var ret = new Spell();
            try
            {
                frame = frame.Spawn(HeaderTranslation.ParseRecord(
                    frame,
                    Spell_Registration.SPEL_HEADER));
                using (frame)
                {
                    Fill_Binary_Structs(
                        item: ret,
                        frame: frame,
                        errorMask: errorMask);
                    while (!frame.Complete)
                    {
                        var parsed = Fill_Binary_RecordTypes(
                            item: ret,
                            frame: frame,
                            errorMask: errorMask);
                        if (parsed.Failed) break;
                    }
                }
            }
            catch (Exception ex)
            when (errorMask != null)
            {
                errorMask().Overall = ex;
            }
            return ret;
        }

        protected static void Fill_Binary_Structs(
            Spell item,
            MutagenFrame frame,
            Func<Spell_ErrorMask> errorMask)
        {
            NamedMajorRecord.Fill_Binary_Structs(
                item: item,
                frame: frame,
                errorMask: errorMask);
        }

        protected static TryGet<Spell_FieldIndex?> Fill_Binary_RecordTypes(
            Spell item,
            MutagenFrame frame,
            Func<Spell_ErrorMask> errorMask)
        {
            var nextRecordType = HeaderTranslation.GetNextSubRecordType(
                frame: frame,
                contentLength: out var contentLength);
            switch (nextRecordType.Type)
            {
                case "SPIT":
                    frame.Position += Constants.SUBRECORD_LENGTH;
                    using (var dataFrame = frame.Spawn(contentLength))
                    {
                        var TypetryGet = Mutagen.Bethesda.Binary.EnumBinaryTranslation<Spell.SpellType>.Instance.Parse(
                            frame: dataFrame.Spawn(new ContentLength(4)),
                            fieldIndex: (int)Spell_FieldIndex.Type,
                            errorMask: errorMask);
                        item._Type.SetIfSucceeded(TypetryGet);
                        item._Cost.SetIfSucceeded(Mutagen.Bethesda.Binary.UInt32BinaryTranslation.Instance.Parse(
                            frame: dataFrame,
                            fieldIndex: (int)Spell_FieldIndex.Cost,
                            errorMask: errorMask));
                        var LeveltryGet = Mutagen.Bethesda.Binary.EnumBinaryTranslation<Spell.SpellLevel>.Instance.Parse(
                            frame: dataFrame.Spawn(new ContentLength(4)),
                            fieldIndex: (int)Spell_FieldIndex.Level,
                            errorMask: errorMask);
                        item._Level.SetIfSucceeded(LeveltryGet);
                        var FlagtryGet = Mutagen.Bethesda.Binary.EnumBinaryTranslation<Spell.SpellFlag>.Instance.Parse(
                            frame: dataFrame.Spawn(new ContentLength(4)),
                            fieldIndex: (int)Spell_FieldIndex.Flag,
                            errorMask: errorMask);
                        item._Flag.SetIfSucceeded(FlagtryGet);
                    }
                    return TryGet<Spell_FieldIndex?>.Succeed(Spell_FieldIndex.Flag);
                case "EFID":
                    var EffectstryGet = Mutagen.Bethesda.Binary.ListBinaryTranslation<Effect, MaskItem<Exception, Effect_ErrorMask>>.Instance.ParseRepeatedItem(
                        frame: frame,
                        triggeringRecord: Spell_Registration.EFID_HEADER,
                        fieldIndex: (int)Spell_FieldIndex.Effects,
                        objType: ObjectType.Subrecord,
                        errorMask: errorMask,
                        transl: (MutagenFrame r, bool listDoMasks, out MaskItem<Exception, Effect_ErrorMask> listSubMask) =>
                        {
                            return LoquiBinaryTranslation<Effect, Effect_ErrorMask>.Instance.Parse(
                                frame: r.Spawn(snapToFinalPosition: false),
                                doMasks: listDoMasks,
                                errorMask: out listSubMask);
                        }
                        );
                    item._Effects.SetIfSucceeded(EffectstryGet);
                    return TryGet<Spell_FieldIndex?>.Succeed(Spell_FieldIndex.Effects);
                default:
                    return NamedMajorRecord.Fill_Binary_RecordTypes(
                        item: item,
                        frame: frame,
                        errorMask: errorMask).Bubble((i) => SpellCommon.ConvertFieldIndex(i));
            }
        }

        #endregion

        public Spell Copy(
            Spell_CopyMask copyMask = null,
            ISpellGetter def = null)
        {
            return Spell.Copy(
                this,
                copyMask: copyMask,
                def: def);
        }

        public static Spell Copy(
            ISpell item,
            Spell_CopyMask copyMask = null,
            ISpellGetter def = null)
        {
            Spell ret;
            if (item.GetType().Equals(typeof(Spell)))
            {
                ret = new Spell();
            }
            else
            {
                ret = (Spell)Activator.CreateInstance(item.GetType());
            }
            ret.CopyFieldsFrom(
                item,
                copyMask: copyMask,
                def: def);
            return ret;
        }

        public static CopyType CopyGeneric<CopyType>(
            CopyType item,
            Spell_CopyMask copyMask = null,
            ISpellGetter def = null)
            where CopyType : class, ISpell
        {
            CopyType ret;
            if (item.GetType().Equals(typeof(Spell)))
            {
                ret = new Spell() as CopyType;
            }
            else
            {
                ret = (CopyType)Activator.CreateInstance(item.GetType());
            }
            ret.CopyFieldsFrom(
                item,
                copyMask: copyMask,
                doMasks: false,
                errorMask: null,
                cmds: null,
                def: def);
            return ret;
        }

        public static Spell Copy_ToLoqui(
            ISpellGetter item,
            Spell_CopyMask copyMask = null,
            ISpellGetter def = null)
        {
            Spell ret;
            if (item.GetType().Equals(typeof(Spell)))
            {
                ret = new Spell() as Spell;
            }
            else
            {
                ret = (Spell)Activator.CreateInstance(item.GetType());
            }
            ret.CopyFieldsFrom(
                item,
                copyMask: copyMask,
                def: def);
            return ret;
        }

        protected override void SetNthObject(ushort index, object obj, NotifyingFireParameters? cmds = null)
        {
            Spell_FieldIndex enu = (Spell_FieldIndex)index;
            switch (enu)
            {
                case Spell_FieldIndex.Type:
                    this._Type.Set(
                        (Spell.SpellType)obj,
                        cmds);
                    break;
                case Spell_FieldIndex.Cost:
                    this._Cost.Set(
                        (UInt32)obj,
                        cmds);
                    break;
                case Spell_FieldIndex.Level:
                    this._Level.Set(
                        (Spell.SpellLevel)obj,
                        cmds);
                    break;
                case Spell_FieldIndex.Flag:
                    this._Flag.Set(
                        (Spell.SpellFlag)obj,
                        cmds);
                    break;
                case Spell_FieldIndex.Effects:
                    this._Effects.SetTo((IEnumerable<Effect>)obj, cmds);
                    break;
                default:
                    base.SetNthObject(index, obj, cmds);
                    break;
            }
        }

        public override void Clear(NotifyingUnsetParameters? cmds = null)
        {
            CallClearPartial_Internal(cmds);
            SpellCommon.Clear(this, cmds);
        }


        public new static Spell Create(IEnumerable<KeyValuePair<ushort, object>> fields)
        {
            var ret = new Spell();
            foreach (var pair in fields)
            {
                CopyInInternal_Spell(ret, pair);
            }
            return ret;
        }

        protected new static void CopyInInternal_Spell(Spell obj, KeyValuePair<ushort, object> pair)
        {
            if (!EnumExt.TryParse(pair.Key, out Spell_FieldIndex enu))
            {
                CopyInInternal_NamedMajorRecord(obj, pair);
            }
            switch (enu)
            {
                case Spell_FieldIndex.Type:
                    obj._Type.Set(
                        (Spell.SpellType)pair.Value,
                        null);
                    break;
                case Spell_FieldIndex.Cost:
                    obj._Cost.Set(
                        (UInt32)pair.Value,
                        null);
                    break;
                case Spell_FieldIndex.Level:
                    obj._Level.Set(
                        (Spell.SpellLevel)pair.Value,
                        null);
                    break;
                case Spell_FieldIndex.Flag:
                    obj._Flag.Set(
                        (Spell.SpellFlag)pair.Value,
                        null);
                    break;
                case Spell_FieldIndex.Effects:
                    obj._Effects.SetTo((IEnumerable<Effect>)pair.Value, null);
                    break;
                default:
                    throw new ArgumentException($"Unknown enum type: {enu}");
            }
        }
        public static void CopyIn(IEnumerable<KeyValuePair<ushort, object>> fields, Spell obj)
        {
            ILoquiObjectExt.CopyFieldsIn(obj, fields, def: null, skipProtected: false, cmds: null);
        }

    }
    #endregion

    #region Interface
    public interface ISpell : ISpellGetter, INamedMajorRecord, ILoquiClass<ISpell, ISpellGetter>, ILoquiClass<Spell, ISpellGetter>
    {
        new Spell.SpellType Type { get; set; }
        new INotifyingSetItem<Spell.SpellType> Type_Property { get; }

        new UInt32 Cost { get; set; }
        new INotifyingSetItem<UInt32> Cost_Property { get; }

        new Spell.SpellLevel Level { get; set; }
        new INotifyingSetItem<Spell.SpellLevel> Level_Property { get; }

        new Spell.SpellFlag Flag { get; set; }
        new INotifyingSetItem<Spell.SpellFlag> Flag_Property { get; }

        new INotifyingList<Effect> Effects { get; }
    }

    public interface ISpellGetter : INamedMajorRecordGetter
    {
        #region Type
        Spell.SpellType Type { get; }
        INotifyingSetItemGetter<Spell.SpellType> Type_Property { get; }

        #endregion
        #region Cost
        UInt32 Cost { get; }
        INotifyingSetItemGetter<UInt32> Cost_Property { get; }

        #endregion
        #region Level
        Spell.SpellLevel Level { get; }
        INotifyingSetItemGetter<Spell.SpellLevel> Level_Property { get; }

        #endregion
        #region Flag
        Spell.SpellFlag Flag { get; }
        INotifyingSetItemGetter<Spell.SpellFlag> Flag_Property { get; }

        #endregion
        #region Effects
        INotifyingListGetter<Effect> Effects { get; }
        #endregion

    }

    #endregion

}

namespace Mutagen.Bethesda.Oblivion.Internals
{
    #region Field Index
    public enum Spell_FieldIndex
    {
        MajorRecordFlags = 0,
        FormID = 1,
        Version = 2,
        EditorID = 3,
        RecordType = 4,
        Name = 5,
        Type = 6,
        Cost = 7,
        Level = 8,
        Flag = 9,
        Effects = 10,
    }
    #endregion

    #region Registration
    public class Spell_Registration : ILoquiRegistration
    {
        public static readonly Spell_Registration Instance = new Spell_Registration();

        public static ProtocolKey ProtocolKey => ProtocolDefinition_Oblivion.ProtocolKey;

        public static readonly ObjectKey ObjectKey = new ObjectKey(
            protocolKey: ProtocolDefinition_Oblivion.ProtocolKey,
            msgID: 28,
            version: 0);

        public const string GUID = "6e7673df-39d3-4704-b1ef-ac774f9d01c3";

        public const ushort FieldCount = 5;

        public static readonly Type MaskType = typeof(Spell_Mask<>);

        public static readonly Type ErrorMaskType = typeof(Spell_ErrorMask);

        public static readonly Type ClassType = typeof(Spell);

        public static readonly Type GetterType = typeof(ISpellGetter);

        public static readonly Type SetterType = typeof(ISpell);

        public static readonly Type CommonType = typeof(SpellCommon);

        public const string FullName = "Mutagen.Bethesda.Oblivion.Spell";

        public const string Name = "Spell";

        public const string Namespace = "Mutagen.Bethesda.Oblivion";

        public const byte GenericCount = 0;

        public static readonly Type GenericRegistrationType = null;

        public static ushort? GetNameIndex(StringCaseAgnostic str)
        {
            switch (str.Upper)
            {
                case "TYPE":
                    return (ushort)Spell_FieldIndex.Type;
                case "COST":
                    return (ushort)Spell_FieldIndex.Cost;
                case "LEVEL":
                    return (ushort)Spell_FieldIndex.Level;
                case "FLAG":
                    return (ushort)Spell_FieldIndex.Flag;
                case "EFFECTS":
                    return (ushort)Spell_FieldIndex.Effects;
                default:
                    return null;
            }
        }

        public static bool GetNthIsEnumerable(ushort index)
        {
            Spell_FieldIndex enu = (Spell_FieldIndex)index;
            switch (enu)
            {
                case Spell_FieldIndex.Effects:
                    return true;
                case Spell_FieldIndex.Type:
                case Spell_FieldIndex.Cost:
                case Spell_FieldIndex.Level:
                case Spell_FieldIndex.Flag:
                    return false;
                default:
                    return NamedMajorRecord_Registration.GetNthIsEnumerable(index);
            }
        }

        public static bool GetNthIsLoqui(ushort index)
        {
            Spell_FieldIndex enu = (Spell_FieldIndex)index;
            switch (enu)
            {
                case Spell_FieldIndex.Effects:
                    return true;
                case Spell_FieldIndex.Type:
                case Spell_FieldIndex.Cost:
                case Spell_FieldIndex.Level:
                case Spell_FieldIndex.Flag:
                    return false;
                default:
                    return NamedMajorRecord_Registration.GetNthIsLoqui(index);
            }
        }

        public static bool GetNthIsSingleton(ushort index)
        {
            Spell_FieldIndex enu = (Spell_FieldIndex)index;
            switch (enu)
            {
                case Spell_FieldIndex.Type:
                case Spell_FieldIndex.Cost:
                case Spell_FieldIndex.Level:
                case Spell_FieldIndex.Flag:
                case Spell_FieldIndex.Effects:
                    return false;
                default:
                    return NamedMajorRecord_Registration.GetNthIsSingleton(index);
            }
        }

        public static string GetNthName(ushort index)
        {
            Spell_FieldIndex enu = (Spell_FieldIndex)index;
            switch (enu)
            {
                case Spell_FieldIndex.Type:
                    return "Type";
                case Spell_FieldIndex.Cost:
                    return "Cost";
                case Spell_FieldIndex.Level:
                    return "Level";
                case Spell_FieldIndex.Flag:
                    return "Flag";
                case Spell_FieldIndex.Effects:
                    return "Effects";
                default:
                    return NamedMajorRecord_Registration.GetNthName(index);
            }
        }

        public static bool IsNthDerivative(ushort index)
        {
            Spell_FieldIndex enu = (Spell_FieldIndex)index;
            switch (enu)
            {
                case Spell_FieldIndex.Type:
                case Spell_FieldIndex.Cost:
                case Spell_FieldIndex.Level:
                case Spell_FieldIndex.Flag:
                case Spell_FieldIndex.Effects:
                    return false;
                default:
                    return NamedMajorRecord_Registration.IsNthDerivative(index);
            }
        }

        public static bool IsProtected(ushort index)
        {
            Spell_FieldIndex enu = (Spell_FieldIndex)index;
            switch (enu)
            {
                case Spell_FieldIndex.Type:
                case Spell_FieldIndex.Cost:
                case Spell_FieldIndex.Level:
                case Spell_FieldIndex.Flag:
                case Spell_FieldIndex.Effects:
                    return false;
                default:
                    return NamedMajorRecord_Registration.IsProtected(index);
            }
        }

        public static Type GetNthType(ushort index)
        {
            Spell_FieldIndex enu = (Spell_FieldIndex)index;
            switch (enu)
            {
                case Spell_FieldIndex.Type:
                    return typeof(Spell.SpellType);
                case Spell_FieldIndex.Cost:
                    return typeof(UInt32);
                case Spell_FieldIndex.Level:
                    return typeof(Spell.SpellLevel);
                case Spell_FieldIndex.Flag:
                    return typeof(Spell.SpellFlag);
                case Spell_FieldIndex.Effects:
                    return typeof(NotifyingList<Effect>);
                default:
                    return NamedMajorRecord_Registration.GetNthType(index);
            }
        }

        public static readonly RecordType SPEL_HEADER = new RecordType("SPEL");
        public static readonly RecordType SPIT_HEADER = new RecordType("SPIT");
        public static readonly RecordType EFID_HEADER = new RecordType("EFID");
        public static readonly RecordType TRIGGERING_RECORD_TYPE = SPEL_HEADER;
        public const int NumStructFields = 0;
        public const int NumTypedFields = 1;
        #region Interface
        ProtocolKey ILoquiRegistration.ProtocolKey => ProtocolKey;
        ObjectKey ILoquiRegistration.ObjectKey => ObjectKey;
        string ILoquiRegistration.GUID => GUID;
        int ILoquiRegistration.FieldCount => FieldCount;
        Type ILoquiRegistration.MaskType => MaskType;
        Type ILoquiRegistration.ErrorMaskType => ErrorMaskType;
        Type ILoquiRegistration.ClassType => ClassType;
        Type ILoquiRegistration.SetterType => SetterType;
        Type ILoquiRegistration.GetterType => GetterType;
        Type ILoquiRegistration.CommonType => CommonType;
        string ILoquiRegistration.FullName => FullName;
        string ILoquiRegistration.Name => Name;
        string ILoquiRegistration.Namespace => Namespace;
        byte ILoquiRegistration.GenericCount => GenericCount;
        Type ILoquiRegistration.GenericRegistrationType => GenericRegistrationType;
        ushort? ILoquiRegistration.GetNameIndex(StringCaseAgnostic name) => GetNameIndex(name);
        bool ILoquiRegistration.GetNthIsEnumerable(ushort index) => GetNthIsEnumerable(index);
        bool ILoquiRegistration.GetNthIsLoqui(ushort index) => GetNthIsLoqui(index);
        bool ILoquiRegistration.GetNthIsSingleton(ushort index) => GetNthIsSingleton(index);
        string ILoquiRegistration.GetNthName(ushort index) => GetNthName(index);
        bool ILoquiRegistration.IsNthDerivative(ushort index) => IsNthDerivative(index);
        bool ILoquiRegistration.IsProtected(ushort index) => IsProtected(index);
        Type ILoquiRegistration.GetNthType(ushort index) => GetNthType(index);
        #endregion

    }
    #endregion

    #region Extensions
    public static partial class SpellCommon
    {
        #region Copy Fields From
        public static void CopyFieldsFrom(
            this ISpell item,
            ISpellGetter rhs,
            Spell_CopyMask copyMask = null,
            ISpellGetter def = null,
            NotifyingFireParameters? cmds = null)
        {
            SpellCommon.CopyFieldsFrom(
                item: item,
                rhs: rhs,
                def: def,
                doMasks: false,
                errorMask: null,
                copyMask: copyMask,
                cmds: cmds);
        }

        public static void CopyFieldsFrom(
            this ISpell item,
            ISpellGetter rhs,
            out Spell_ErrorMask errorMask,
            Spell_CopyMask copyMask = null,
            ISpellGetter def = null,
            NotifyingFireParameters? cmds = null)
        {
            SpellCommon.CopyFieldsFrom(
                item: item,
                rhs: rhs,
                def: def,
                doMasks: true,
                errorMask: out errorMask,
                copyMask: copyMask,
                cmds: cmds);
        }

        public static void CopyFieldsFrom(
            this ISpell item,
            ISpellGetter rhs,
            ISpellGetter def,
            bool doMasks,
            out Spell_ErrorMask errorMask,
            Spell_CopyMask copyMask,
            NotifyingFireParameters? cmds)
        {
            Spell_ErrorMask retErrorMask = null;
            Func<Spell_ErrorMask> maskGetter = () =>
            {
                if (retErrorMask == null)
                {
                    retErrorMask = new Spell_ErrorMask();
                }
                return retErrorMask;
            };
            CopyFieldsFrom(
                item: item,
                rhs: rhs,
                def: def,
                doMasks: true,
                errorMask: maskGetter,
                copyMask: copyMask,
                cmds: cmds);
            errorMask = retErrorMask;
        }

        public static void CopyFieldsFrom(
            this ISpell item,
            ISpellGetter rhs,
            ISpellGetter def,
            bool doMasks,
            Func<Spell_ErrorMask> errorMask,
            Spell_CopyMask copyMask,
            NotifyingFireParameters? cmds)
        {
            NamedMajorRecordCommon.CopyFieldsFrom(
                item,
                rhs,
                def,
                doMasks,
                errorMask,
                copyMask,
                cmds);
            if (copyMask?.Type ?? true)
            {
                try
                {
                    item.Type_Property.SetToWithDefault(
                        rhs: rhs.Type_Property,
                        def: def?.Type_Property,
                        cmds: cmds);
                }
                catch (Exception ex)
                when (doMasks)
                {
                    errorMask().SetNthException((int)Spell_FieldIndex.Type, ex);
                }
            }
            if (copyMask?.Cost ?? true)
            {
                try
                {
                    item.Cost_Property.SetToWithDefault(
                        rhs: rhs.Cost_Property,
                        def: def?.Cost_Property,
                        cmds: cmds);
                }
                catch (Exception ex)
                when (doMasks)
                {
                    errorMask().SetNthException((int)Spell_FieldIndex.Cost, ex);
                }
            }
            if (copyMask?.Level ?? true)
            {
                try
                {
                    item.Level_Property.SetToWithDefault(
                        rhs: rhs.Level_Property,
                        def: def?.Level_Property,
                        cmds: cmds);
                }
                catch (Exception ex)
                when (doMasks)
                {
                    errorMask().SetNthException((int)Spell_FieldIndex.Level, ex);
                }
            }
            if (copyMask?.Flag ?? true)
            {
                try
                {
                    item.Flag_Property.SetToWithDefault(
                        rhs: rhs.Flag_Property,
                        def: def?.Flag_Property,
                        cmds: cmds);
                }
                catch (Exception ex)
                when (doMasks)
                {
                    errorMask().SetNthException((int)Spell_FieldIndex.Flag, ex);
                }
            }
            if (copyMask?.Effects.Overall != CopyOption.Skip)
            {
                try
                {
                    item.Effects.SetToWithDefault(
                        rhs.Effects,
                        def?.Effects,
                        cmds,
                        (r, d) =>
                        {
                            switch (copyMask?.Effects.Overall ?? CopyOption.Reference)
                            {
                                case CopyOption.Reference:
                                    return r;
                                case CopyOption.MakeCopy:
                                    if (r == null) return default(Effect);
                                    return Effect.Copy(
                                        r,
                                        copyMask?.Effects?.Specific,
                                        def: d);
                                default:
                                    throw new NotImplementedException($"Unknown CopyOption {copyMask?.Effects.Overall}. Cannot execute copy.");
                            }
                        }
                        );
                }
                catch (Exception ex)
                when (doMasks)
                {
                    errorMask().SetNthException((int)Spell_FieldIndex.Effects, ex);
                }
            }
        }

        #endregion

        public static void SetNthObjectHasBeenSet(
            ushort index,
            bool on,
            ISpell obj,
            NotifyingFireParameters? cmds = null)
        {
            Spell_FieldIndex enu = (Spell_FieldIndex)index;
            switch (enu)
            {
                case Spell_FieldIndex.Type:
                    obj.Type_Property.HasBeenSet = on;
                    break;
                case Spell_FieldIndex.Cost:
                    obj.Cost_Property.HasBeenSet = on;
                    break;
                case Spell_FieldIndex.Level:
                    obj.Level_Property.HasBeenSet = on;
                    break;
                case Spell_FieldIndex.Flag:
                    obj.Flag_Property.HasBeenSet = on;
                    break;
                case Spell_FieldIndex.Effects:
                    obj.Effects.HasBeenSet = on;
                    break;
                default:
                    NamedMajorRecordCommon.SetNthObjectHasBeenSet(index, on, obj);
                    break;
            }
        }

        public static void UnsetNthObject(
            ushort index,
            ISpell obj,
            NotifyingUnsetParameters? cmds = null)
        {
            Spell_FieldIndex enu = (Spell_FieldIndex)index;
            switch (enu)
            {
                case Spell_FieldIndex.Type:
                    obj.Type_Property.Unset(cmds);
                    break;
                case Spell_FieldIndex.Cost:
                    obj.Cost_Property.Unset(cmds);
                    break;
                case Spell_FieldIndex.Level:
                    obj.Level_Property.Unset(cmds);
                    break;
                case Spell_FieldIndex.Flag:
                    obj.Flag_Property.Unset(cmds);
                    break;
                case Spell_FieldIndex.Effects:
                    obj.Effects.Unset(cmds);
                    break;
                default:
                    NamedMajorRecordCommon.UnsetNthObject(index, obj);
                    break;
            }
        }

        public static bool GetNthObjectHasBeenSet(
            ushort index,
            ISpell obj)
        {
            Spell_FieldIndex enu = (Spell_FieldIndex)index;
            switch (enu)
            {
                case Spell_FieldIndex.Type:
                    return obj.Type_Property.HasBeenSet;
                case Spell_FieldIndex.Cost:
                    return obj.Cost_Property.HasBeenSet;
                case Spell_FieldIndex.Level:
                    return obj.Level_Property.HasBeenSet;
                case Spell_FieldIndex.Flag:
                    return obj.Flag_Property.HasBeenSet;
                case Spell_FieldIndex.Effects:
                    return obj.Effects.HasBeenSet;
                default:
                    return NamedMajorRecordCommon.GetNthObjectHasBeenSet(index, obj);
            }
        }

        public static object GetNthObject(
            ushort index,
            ISpellGetter obj)
        {
            Spell_FieldIndex enu = (Spell_FieldIndex)index;
            switch (enu)
            {
                case Spell_FieldIndex.Type:
                    return obj.Type;
                case Spell_FieldIndex.Cost:
                    return obj.Cost;
                case Spell_FieldIndex.Level:
                    return obj.Level;
                case Spell_FieldIndex.Flag:
                    return obj.Flag;
                case Spell_FieldIndex.Effects:
                    return obj.Effects;
                default:
                    return NamedMajorRecordCommon.GetNthObject(index, obj);
            }
        }

        public static void Clear(
            ISpell item,
            NotifyingUnsetParameters? cmds = null)
        {
            item.Type_Property.Unset(cmds.ToUnsetParams());
            item.Cost_Property.Unset(cmds.ToUnsetParams());
            item.Level_Property.Unset(cmds.ToUnsetParams());
            item.Flag_Property.Unset(cmds.ToUnsetParams());
            item.Effects.Unset(cmds.ToUnsetParams());
        }

        public static Spell_Mask<bool> GetEqualsMask(
            this ISpellGetter item,
            ISpellGetter rhs)
        {
            var ret = new Spell_Mask<bool>();
            FillEqualsMask(item, rhs, ret);
            return ret;
        }

        public static void FillEqualsMask(
            ISpellGetter item,
            ISpellGetter rhs,
            Spell_Mask<bool> ret)
        {
            if (rhs == null) return;
            ret.Type = item.Type_Property.Equals(rhs.Type_Property, (l, r) => l == r);
            ret.Cost = item.Cost_Property.Equals(rhs.Cost_Property, (l, r) => l == r);
            ret.Level = item.Level_Property.Equals(rhs.Level_Property, (l, r) => l == r);
            ret.Flag = item.Flag_Property.Equals(rhs.Flag_Property, (l, r) => l == r);
            if (item.Effects.HasBeenSet == rhs.Effects.HasBeenSet)
            {
                if (item.Effects.HasBeenSet)
                {
                    ret.Effects = new MaskItem<bool, IEnumerable<MaskItem<bool, Effect_Mask<bool>>>>();
                    ret.Effects.Specific = item.Effects.SelectAgainst<Effect, MaskItem<bool, Effect_Mask<bool>>>(rhs.Effects, ((l, r) =>
                    {
                        MaskItem<bool, Effect_Mask<bool>> itemRet;
                        itemRet = l.LoquiEqualsHelper(r, (loqLhs, loqRhs) => EffectCommon.GetEqualsMask(loqLhs, loqRhs));
                        return itemRet;
                    }
                    ), out ret.Effects.Overall);
                    ret.Effects.Overall = ret.Effects.Overall && ret.Effects.Specific.All((b) => b.Overall);
                }
                else
                {
                    ret.Effects = new MaskItem<bool, IEnumerable<MaskItem<bool, Effect_Mask<bool>>>>();
                    ret.Effects.Overall = true;
                }
            }
            else
            {
                ret.Effects = new MaskItem<bool, IEnumerable<MaskItem<bool, Effect_Mask<bool>>>>();
                ret.Effects.Overall = false;
            }
            NamedMajorRecordCommon.FillEqualsMask(item, rhs, ret);
        }

        public static string ToString(
            this ISpellGetter item,
            string name = null,
            Spell_Mask<bool> printMask = null)
        {
            var fg = new FileGeneration();
            item.ToString(fg, name, printMask);
            return fg.ToString();
        }

        public static void ToString(
            this ISpellGetter item,
            FileGeneration fg,
            string name = null,
            Spell_Mask<bool> printMask = null)
        {
            if (name == null)
            {
                fg.AppendLine($"{nameof(Spell)} =>");
            }
            else
            {
                fg.AppendLine($"{name} ({nameof(Spell)}) =>");
            }
            fg.AppendLine("[");
            using (new DepthWrapper(fg))
            {
                if (printMask?.Type ?? true)
                {
                    fg.AppendLine($"Type => {item.Type}");
                }
                if (printMask?.Cost ?? true)
                {
                    fg.AppendLine($"Cost => {item.Cost}");
                }
                if (printMask?.Level ?? true)
                {
                    fg.AppendLine($"Level => {item.Level}");
                }
                if (printMask?.Flag ?? true)
                {
                    fg.AppendLine($"Flag => {item.Flag}");
                }
                if (printMask?.Effects?.Overall ?? true)
                {
                    fg.AppendLine("Effects =>");
                    fg.AppendLine("[");
                    using (new DepthWrapper(fg))
                    {
                        foreach (var subItem in item.Effects)
                        {
                            fg.AppendLine("[");
                            using (new DepthWrapper(fg))
                            {
                                subItem?.ToString(fg, "Item");
                            }
                            fg.AppendLine("]");
                        }
                    }
                    fg.AppendLine("]");
                }
            }
            fg.AppendLine("]");
        }

        public static bool HasBeenSet(
            this ISpellGetter item,
            Spell_Mask<bool?> checkMask)
        {
            if (checkMask.Type.HasValue && checkMask.Type.Value != item.Type_Property.HasBeenSet) return false;
            if (checkMask.Cost.HasValue && checkMask.Cost.Value != item.Cost_Property.HasBeenSet) return false;
            if (checkMask.Level.HasValue && checkMask.Level.Value != item.Level_Property.HasBeenSet) return false;
            if (checkMask.Flag.HasValue && checkMask.Flag.Value != item.Flag_Property.HasBeenSet) return false;
            if (checkMask.Effects.Overall.HasValue && checkMask.Effects.Overall.Value != item.Effects.HasBeenSet) return false;
            return true;
        }

        public static Spell_Mask<bool> GetHasBeenSetMask(ISpellGetter item)
        {
            var ret = new Spell_Mask<bool>();
            ret.Type = item.Type_Property.HasBeenSet;
            ret.Cost = item.Cost_Property.HasBeenSet;
            ret.Level = item.Level_Property.HasBeenSet;
            ret.Flag = item.Flag_Property.HasBeenSet;
            ret.Effects = new MaskItem<bool, IEnumerable<MaskItem<bool, Effect_Mask<bool>>>>(item.Effects.HasBeenSet, item.Effects.Select((i) => new MaskItem<bool, Effect_Mask<bool>>(true, i.GetHasBeenSetMask())));
            return ret;
        }

        public static Spell_FieldIndex? ConvertFieldIndex(NamedMajorRecord_FieldIndex? index)
        {
            if (!index.HasValue) return null;
            return ConvertFieldIndex(index: index.Value);
        }

        public static Spell_FieldIndex ConvertFieldIndex(NamedMajorRecord_FieldIndex index)
        {
            switch (index)
            {
                case NamedMajorRecord_FieldIndex.MajorRecordFlags:
                    return (Spell_FieldIndex)((int)index);
                case NamedMajorRecord_FieldIndex.FormID:
                    return (Spell_FieldIndex)((int)index);
                case NamedMajorRecord_FieldIndex.Version:
                    return (Spell_FieldIndex)((int)index);
                case NamedMajorRecord_FieldIndex.EditorID:
                    return (Spell_FieldIndex)((int)index);
                case NamedMajorRecord_FieldIndex.RecordType:
                    return (Spell_FieldIndex)((int)index);
                case NamedMajorRecord_FieldIndex.Name:
                    return (Spell_FieldIndex)((int)index);
                default:
                    throw new ArgumentException($"Index is out of range: {index.ToStringFast_Enum_Only()}");
            }
        }

        public static Spell_FieldIndex? ConvertFieldIndex(MajorRecord_FieldIndex? index)
        {
            if (!index.HasValue) return null;
            return ConvertFieldIndex(index: index.Value);
        }

        public static Spell_FieldIndex ConvertFieldIndex(MajorRecord_FieldIndex index)
        {
            switch (index)
            {
                case MajorRecord_FieldIndex.MajorRecordFlags:
                    return (Spell_FieldIndex)((int)index);
                case MajorRecord_FieldIndex.FormID:
                    return (Spell_FieldIndex)((int)index);
                case MajorRecord_FieldIndex.Version:
                    return (Spell_FieldIndex)((int)index);
                case MajorRecord_FieldIndex.EditorID:
                    return (Spell_FieldIndex)((int)index);
                case MajorRecord_FieldIndex.RecordType:
                    return (Spell_FieldIndex)((int)index);
                default:
                    throw new ArgumentException($"Index is out of range: {index.ToStringFast_Enum_Only()}");
            }
        }

        #region XML Translation
        #region XML Write
        public static void Write_XML(
            XmlWriter writer,
            ISpellGetter item,
            bool doMasks,
            out Spell_ErrorMask errorMask,
            string name = null)
        {
            Spell_ErrorMask errMaskRet = null;
            Write_XML_Internal(
                writer: writer,
                name: name,
                item: item,
                errorMask: doMasks ? () => errMaskRet ?? (errMaskRet = new Spell_ErrorMask()) : default(Func<Spell_ErrorMask>));
            errorMask = errMaskRet;
        }

        private static void Write_XML_Internal(
            XmlWriter writer,
            ISpellGetter item,
            Func<Spell_ErrorMask> errorMask,
            string name = null)
        {
            try
            {
                using (new ElementWrapper(writer, name ?? "Mutagen.Bethesda.Oblivion.Spell"))
                {
                    if (name != null)
                    {
                        writer.WriteAttributeString("type", "Mutagen.Bethesda.Oblivion.Spell");
                    }
                    if (item.Type_Property.HasBeenSet)
                    {
                        EnumXmlTranslation<Spell.SpellType>.Instance.Write(
                            writer: writer,
                            name: nameof(item.Type),
                            item: item.Type_Property,
                            fieldIndex: (int)Spell_FieldIndex.Type,
                            errorMask: errorMask);
                    }
                    if (item.Cost_Property.HasBeenSet)
                    {
                        UInt32XmlTranslation.Instance.Write(
                            writer: writer,
                            name: nameof(item.Cost),
                            item: item.Cost_Property,
                            fieldIndex: (int)Spell_FieldIndex.Cost,
                            errorMask: errorMask);
                    }
                    if (item.Level_Property.HasBeenSet)
                    {
                        EnumXmlTranslation<Spell.SpellLevel>.Instance.Write(
                            writer: writer,
                            name: nameof(item.Level),
                            item: item.Level_Property,
                            fieldIndex: (int)Spell_FieldIndex.Level,
                            errorMask: errorMask);
                    }
                    if (item.Flag_Property.HasBeenSet)
                    {
                        EnumXmlTranslation<Spell.SpellFlag>.Instance.Write(
                            writer: writer,
                            name: nameof(item.Flag),
                            item: item.Flag_Property,
                            fieldIndex: (int)Spell_FieldIndex.Flag,
                            errorMask: errorMask);
                    }
                    if (item.Effects.HasBeenSet)
                    {
                        ListXmlTranslation<Effect, MaskItem<Exception, Effect_ErrorMask>>.Instance.Write(
                            writer: writer,
                            name: nameof(item.Effects),
                            item: item.Effects,
                            fieldIndex: (int)Spell_FieldIndex.Effects,
                            errorMask: errorMask,
                            transl: (Effect subItem, bool listDoMasks, out MaskItem<Exception, Effect_ErrorMask> listSubMask) =>
                            {
                                LoquiXmlTranslation<Effect, Effect_ErrorMask>.Instance.Write(
                                    writer: writer,
                                    item: subItem,
                                    name: "Item",
                                    doMasks: errorMask != null,
                                    errorMask: out listSubMask);
                            }
                            );
                    }
                }
            }
            catch (Exception ex)
            when (errorMask != null)
            {
                errorMask().Overall = ex;
            }
        }
        #endregion

        #endregion

        #region Binary Translation
        #region Binary Write
        public static void Write_Binary(
            MutagenWriter writer,
            ISpellGetter item,
            bool doMasks,
            out Spell_ErrorMask errorMask)
        {
            Spell_ErrorMask errMaskRet = null;
            Write_Binary_Internal(
                writer: writer,
                item: item,
                errorMask: doMasks ? () => errMaskRet ?? (errMaskRet = new Spell_ErrorMask()) : default(Func<Spell_ErrorMask>));
            errorMask = errMaskRet;
        }

        private static void Write_Binary_Internal(
            MutagenWriter writer,
            ISpellGetter item,
            Func<Spell_ErrorMask> errorMask)
        {
            try
            {
                using (HeaderExport.ExportHeader(
                    writer: writer,
                    record: Spell_Registration.SPEL_HEADER,
                    type: ObjectType.Record))
                {
                    MajorRecordCommon.Write_Binary_Embedded(
                        item: item,
                        writer: writer,
                        errorMask: errorMask);
                    Write_Binary_RecordTypes(
                        item: item,
                        writer: writer,
                        errorMask: errorMask);
                }
            }
            catch (Exception ex)
            when (errorMask != null)
            {
                errorMask().Overall = ex;
            }
        }
        #endregion

        public static void Write_Binary_RecordTypes(
            ISpellGetter item,
            MutagenWriter writer,
            Func<Spell_ErrorMask> errorMask)
        {
            NamedMajorRecordCommon.Write_Binary_RecordTypes(
                item: item,
                writer: writer,
                errorMask: errorMask);
            using (HeaderExport.ExportSubRecordHeader(writer, Spell_Registration.SPIT_HEADER))
            {
                Mutagen.Bethesda.Binary.EnumBinaryTranslation<Spell.SpellType>.Instance.Write(
                    writer,
                    item.Type_Property,
                    length: new ContentLength(4),
                    fieldIndex: (int)Spell_FieldIndex.Type,
                    errorMask: errorMask);
                Mutagen.Bethesda.Binary.UInt32BinaryTranslation.Instance.Write(
                    writer: writer,
                    item: item.Cost_Property,
                    fieldIndex: (int)Spell_FieldIndex.Cost,
                    errorMask: errorMask);
                Mutagen.Bethesda.Binary.EnumBinaryTranslation<Spell.SpellLevel>.Instance.Write(
                    writer,
                    item.Level_Property,
                    length: new ContentLength(4),
                    fieldIndex: (int)Spell_FieldIndex.Level,
                    errorMask: errorMask);
                Mutagen.Bethesda.Binary.EnumBinaryTranslation<Spell.SpellFlag>.Instance.Write(
                    writer,
                    item.Flag_Property,
                    length: new ContentLength(4),
                    fieldIndex: (int)Spell_FieldIndex.Flag,
                    errorMask: errorMask);
            }
            Mutagen.Bethesda.Binary.ListBinaryTranslation<Effect, MaskItem<Exception, Effect_ErrorMask>>.Instance.Write(
                writer: writer,
                item: item.Effects,
                fieldIndex: (int)Spell_FieldIndex.Effects,
                errorMask: errorMask,
                transl: (Effect subItem, bool listDoMasks, out MaskItem<Exception, Effect_ErrorMask> listSubMask) =>
                {
                    LoquiBinaryTranslation<Effect, Effect_ErrorMask>.Instance.Write(
                        writer: writer,
                        item: subItem,
                        doMasks: listDoMasks,
                        errorMask: out listSubMask);
                }
                );
        }

        #endregion

    }
    #endregion

    #region Modules

    #region Mask
    public class Spell_Mask<T> : NamedMajorRecord_Mask<T>, IMask<T>, IEquatable<Spell_Mask<T>>
    {
        #region Ctors
        public Spell_Mask()
        {
        }

        public Spell_Mask(T initialValue)
        {
            this.Type = initialValue;
            this.Cost = initialValue;
            this.Level = initialValue;
            this.Flag = initialValue;
            this.Effects = new MaskItem<T, IEnumerable<MaskItem<T, Effect_Mask<T>>>>(initialValue, null);
        }
        #endregion

        #region Members
        public T Type;
        public T Cost;
        public T Level;
        public T Flag;
        public MaskItem<T, IEnumerable<MaskItem<T, Effect_Mask<T>>>> Effects;
        #endregion

        #region Equals
        public override bool Equals(object obj)
        {
            if (!(obj is Spell_Mask<T> rhs)) return false;
            return Equals(rhs);
        }

        public bool Equals(Spell_Mask<T> rhs)
        {
            if (rhs == null) return false;
            if (!base.Equals(rhs)) return false;
            if (!object.Equals(this.Type, rhs.Type)) return false;
            if (!object.Equals(this.Cost, rhs.Cost)) return false;
            if (!object.Equals(this.Level, rhs.Level)) return false;
            if (!object.Equals(this.Flag, rhs.Flag)) return false;
            if (!object.Equals(this.Effects, rhs.Effects)) return false;
            return true;
        }
        public override int GetHashCode()
        {
            int ret = 0;
            ret = ret.CombineHashCode(this.Type?.GetHashCode());
            ret = ret.CombineHashCode(this.Cost?.GetHashCode());
            ret = ret.CombineHashCode(this.Level?.GetHashCode());
            ret = ret.CombineHashCode(this.Flag?.GetHashCode());
            ret = ret.CombineHashCode(this.Effects?.GetHashCode());
            ret = ret.CombineHashCode(base.GetHashCode());
            return ret;
        }

        #endregion

        #region All Equal
        public override bool AllEqual(Func<T, bool> eval)
        {
            if (!base.AllEqual(eval)) return false;
            if (!eval(this.Type)) return false;
            if (!eval(this.Cost)) return false;
            if (!eval(this.Level)) return false;
            if (!eval(this.Flag)) return false;
            if (this.Effects != null)
            {
                if (!eval(this.Effects.Overall)) return false;
                if (this.Effects.Specific != null)
                {
                    foreach (var item in this.Effects.Specific)
                    {
                        if (!eval(item.Overall)) return false;
                        if (item.Specific != null && !item.Specific.AllEqual(eval)) return false;
                    }
                }
            }
            return true;
        }
        #endregion

        #region Translate
        public new Spell_Mask<R> Translate<R>(Func<T, R> eval)
        {
            var ret = new Spell_Mask<R>();
            this.Translate_InternalFill(ret, eval);
            return ret;
        }

        protected void Translate_InternalFill<R>(Spell_Mask<R> obj, Func<T, R> eval)
        {
            base.Translate_InternalFill(obj, eval);
            obj.Type = eval(this.Type);
            obj.Cost = eval(this.Cost);
            obj.Level = eval(this.Level);
            obj.Flag = eval(this.Flag);
            if (Effects != null)
            {
                obj.Effects = new MaskItem<R, IEnumerable<MaskItem<R, Effect_Mask<R>>>>();
                obj.Effects.Overall = eval(this.Effects.Overall);
                if (Effects.Specific != null)
                {
                    List<MaskItem<R, Effect_Mask<R>>> l = new List<MaskItem<R, Effect_Mask<R>>>();
                    obj.Effects.Specific = l;
                    foreach (var item in Effects.Specific)
                    {
                        MaskItem<R, Effect_Mask<R>> mask = default(MaskItem<R, Effect_Mask<R>>);
                        if (item != null)
                        {
                            mask = new MaskItem<R, Effect_Mask<R>>();
                            mask.Overall = eval(item.Overall);
                            if (item.Specific != null)
                            {
                                mask.Specific = item.Specific.Translate(eval);
                            }
                        }
                        l.Add(mask);
                    }
                }
            }
        }
        #endregion

        #region Clear Enumerables
        public override void ClearEnumerables()
        {
            base.ClearEnumerables();
            this.Effects.Specific = null;
        }
        #endregion

        #region To String
        public override string ToString()
        {
            return ToString(printMask: null);
        }

        public string ToString(Spell_Mask<bool> printMask = null)
        {
            var fg = new FileGeneration();
            ToString(fg, printMask);
            return fg.ToString();
        }

        public void ToString(FileGeneration fg, Spell_Mask<bool> printMask = null)
        {
            fg.AppendLine($"{nameof(Spell_Mask<T>)} =>");
            fg.AppendLine("[");
            using (new DepthWrapper(fg))
            {
                if (printMask?.Type ?? true)
                {
                    fg.AppendLine($"Type => {Type}");
                }
                if (printMask?.Cost ?? true)
                {
                    fg.AppendLine($"Cost => {Cost}");
                }
                if (printMask?.Level ?? true)
                {
                    fg.AppendLine($"Level => {Level}");
                }
                if (printMask?.Flag ?? true)
                {
                    fg.AppendLine($"Flag => {Flag}");
                }
                if (printMask?.Effects?.Overall ?? true)
                {
                    fg.AppendLine("Effects =>");
                    fg.AppendLine("[");
                    using (new DepthWrapper(fg))
                    {
                        if (Effects.Overall != null)
                        {
                            fg.AppendLine(Effects.Overall.ToString());
                        }
                        if (Effects.Specific != null)
                        {
                            foreach (var subItem in Effects.Specific)
                            {
                                fg.AppendLine("[");
                                using (new DepthWrapper(fg))
                                {
                                    subItem?.ToString(fg);
                                }
                                fg.AppendLine("]");
                            }
                        }
                    }
                    fg.AppendLine("]");
                }
            }
            fg.AppendLine("]");
        }
        #endregion

    }

    public class Spell_ErrorMask : NamedMajorRecord_ErrorMask, IErrorMask<Spell_ErrorMask>
    {
        #region Members
        public Exception Type;
        public Exception Cost;
        public Exception Level;
        public Exception Flag;
        public MaskItem<Exception, IEnumerable<MaskItem<Exception, Effect_ErrorMask>>> Effects;
        #endregion

        #region IErrorMask
        public override void SetNthException(int index, Exception ex)
        {
            Spell_FieldIndex enu = (Spell_FieldIndex)index;
            switch (enu)
            {
                case Spell_FieldIndex.Type:
                    this.Type = ex;
                    break;
                case Spell_FieldIndex.Cost:
                    this.Cost = ex;
                    break;
                case Spell_FieldIndex.Level:
                    this.Level = ex;
                    break;
                case Spell_FieldIndex.Flag:
                    this.Flag = ex;
                    break;
                case Spell_FieldIndex.Effects:
                    this.Effects = new MaskItem<Exception, IEnumerable<MaskItem<Exception, Effect_ErrorMask>>>(ex, null);
                    break;
                default:
                    base.SetNthException(index, ex);
                    break;
            }
        }

        public override void SetNthMask(int index, object obj)
        {
            Spell_FieldIndex enu = (Spell_FieldIndex)index;
            switch (enu)
            {
                case Spell_FieldIndex.Type:
                    this.Type = (Exception)obj;
                    break;
                case Spell_FieldIndex.Cost:
                    this.Cost = (Exception)obj;
                    break;
                case Spell_FieldIndex.Level:
                    this.Level = (Exception)obj;
                    break;
                case Spell_FieldIndex.Flag:
                    this.Flag = (Exception)obj;
                    break;
                case Spell_FieldIndex.Effects:
                    this.Effects = (MaskItem<Exception, IEnumerable<MaskItem<Exception, Effect_ErrorMask>>>)obj;
                    break;
                default:
                    base.SetNthMask(index, obj);
                    break;
            }
        }

        public override bool IsInError()
        {
            if (Overall != null) return true;
            if (Type != null) return true;
            if (Cost != null) return true;
            if (Level != null) return true;
            if (Flag != null) return true;
            if (Effects != null) return true;
            return false;
        }
        #endregion

        #region To String
        public override string ToString()
        {
            var fg = new FileGeneration();
            ToString(fg);
            return fg.ToString();
        }

        public override void ToString(FileGeneration fg)
        {
            fg.AppendLine("Spell_ErrorMask =>");
            fg.AppendLine("[");
            using (new DepthWrapper(fg))
            {
                if (this.Overall != null)
                {
                    fg.AppendLine("Overall =>");
                    fg.AppendLine("[");
                    using (new DepthWrapper(fg))
                    {
                        fg.AppendLine($"{this.Overall}");
                    }
                    fg.AppendLine("]");
                }
                ToString_FillInternal(fg);
            }
            fg.AppendLine("]");
        }
        protected override void ToString_FillInternal(FileGeneration fg)
        {
            base.ToString_FillInternal(fg);
            fg.AppendLine($"Type => {Type}");
            fg.AppendLine($"Cost => {Cost}");
            fg.AppendLine($"Level => {Level}");
            fg.AppendLine($"Flag => {Flag}");
            fg.AppendLine("Effects =>");
            fg.AppendLine("[");
            using (new DepthWrapper(fg))
            {
                if (Effects.Overall != null)
                {
                    fg.AppendLine(Effects.Overall.ToString());
                }
                if (Effects.Specific != null)
                {
                    foreach (var subItem in Effects.Specific)
                    {
                        fg.AppendLine("[");
                        using (new DepthWrapper(fg))
                        {
                            subItem?.ToString(fg);
                        }
                        fg.AppendLine("]");
                    }
                }
            }
            fg.AppendLine("]");
        }
        #endregion

        #region Combine
        public Spell_ErrorMask Combine(Spell_ErrorMask rhs)
        {
            var ret = new Spell_ErrorMask();
            ret.Type = this.Type.Combine(rhs.Type);
            ret.Cost = this.Cost.Combine(rhs.Cost);
            ret.Level = this.Level.Combine(rhs.Level);
            ret.Flag = this.Flag.Combine(rhs.Flag);
            ret.Effects = new MaskItem<Exception, IEnumerable<MaskItem<Exception, Effect_ErrorMask>>>(this.Effects.Overall.Combine(rhs.Effects.Overall), new List<MaskItem<Exception, Effect_ErrorMask>>(this.Effects.Specific.And(rhs.Effects.Specific)));
            return ret;
        }
        public static Spell_ErrorMask Combine(Spell_ErrorMask lhs, Spell_ErrorMask rhs)
        {
            if (lhs != null && rhs != null) return lhs.Combine(rhs);
            return lhs ?? rhs;
        }
        #endregion

    }
    public class Spell_CopyMask : NamedMajorRecord_CopyMask
    {
        #region Members
        public bool Type;
        public bool Cost;
        public bool Level;
        public bool Flag;
        public MaskItem<CopyOption, Effect_CopyMask> Effects;
        #endregion

    }
    #endregion




    #endregion

}
