namespace Mutagen.Bethesda.Fallout4;

public enum TargetObjectType
{
    None = 0,
    Activators = 1,
    Armor = 2,
    Books = 3,
    Containers = 4,
    Doors = 5,
    Ingredients = 6,
    Lights = 7,
    Miscellaneous = 8,
    Flora = 9,
    Furniture = 10,
    AnyWeapons = 11,
    Ammo = 12,
    Keys = 13,
    Alchemy = 14,
    Food = 15,
    Clothing = 16,
    AllWearable = 17,
    NoWeapons = 18,
    MeleeWeapons = 19,
    RangedWeapons = 20,
    AnySpells = 21,
    TargetSpells = 22,
    TouchSpells =  23,
    SelfSpells = 24,
    AnyActors = 25,
    BedsFurniture = 26,
    ChairsFurniture = 27,
    Shouts = 28,
    HeadtrackMarkers = 29
}