<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
    <RootNamespace>Mutagen.Bethesda.Tests.GUI</RootNamespace>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
    <NoWarn>NU1701</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Noggog.UI" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" />
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="ReactiveUI.Avalonia" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="Noggog.UI.Avalonia" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mutagen.Bethesda.Tests.GUI.Core\Mutagen.Bethesda.Tests.GUI.Core.csproj" />
  </ItemGroup>

</Project>
