namespace Mutagen.Bethesda.Fallout4;

partial class PlacedObjectMapMarker
{
    [Flags]
    public enum Flag
    {
        Visible = 0x01,
        CanTravelTo = 0x02,
        ShowAllIsHidden = 0x04,
        UseLocationName = 0x08
    }

    public enum Types
    {
        Cave = 0,
        City = 1,
        DiamondCity = 2,
        Encampment = 3,
        FactoryOrIndustrialSite = 4,
        GovtBuildingOrMonument = 5,
        MetroStation = 6,
        MilitaryBase = 7,
        NaturalLandmark = 8,
        OfficeOrCivicBuilding = 9,
        RuinsTown = 10,
        RuinsUrban = 11,
        Sanctuary = 12,
        Settlement = 13,
        SewerOrUtilityTunnels = 14,
        Vault = 15,
        Airfield = 16,
        BunkerHill = 17,
        Camper = 18,
        Car = 19,
        Church = 20,
        CountryClub = 21,
        CustomHouse = 22,
        DriveIn = 23,
        ElevatedHighway = 24,
        FaneuilHall = 25,
        Farm = 26,
        FillingStation = 27,
        Forested = 28,
        Goodneighbor = 29,
        Graveyard = 30,
        Hospital = 31,
        IndustrialDome = 32,
        IndustrialStacks = 33,
        Institute = 34,
        IrishPride = 35,
        Junkyard = 36,
        Observatory = 37,
        Pier = 38,
        PondOrLake = 39,
        Quarry = 40,
        RadioactiveArea = 41,
        RadioTower = 42,
        Salem = 43,
        School = 44,
        Shipwreck = 45,
        Submarine = 46,
        SwanPond = 47,
        SynthHead = 48,
        Town = 49,
        BrotherhoodofSteel = 50,
        BrownstoneTownhouse = 51,
        Bunker = 52,
        Castle = 53,
        Skyscraper = 54,
        Libertalia = 55,
        LowRiseBuilding = 56,
        Minutemen = 57,
        PoliceStation = 58,
        Prydwen = 59,
        RailroadFaction = 60,
        Railroad = 61,
        Satellite = 62,
        Sentinel = 63,
        USSConstitution = 64,
        MechanistLairRaidersettlementVassalsettlementPotentialVassalsettlement = 65,
    }
}
