/*
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
 * Autogenerated by Loqui.  Do not manually change.
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
*/
#region Usings
using Loqui;
using Loqui.Interfaces;
using Loqui.Internal;
using Mutagen.Bethesda.Binary;
using Mutagen.Bethesda.Fallout4.Internals;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Plugins.Binary.Headers;
using Mutagen.Bethesda.Plugins.Binary.Overlay;
using Mutagen.Bethesda.Plugins.Binary.Streams;
using Mutagen.Bethesda.Plugins.Binary.Translations;
using Mutagen.Bethesda.Plugins.Exceptions;
using Mutagen.Bethesda.Plugins.Internals;
using Mutagen.Bethesda.Plugins.Meta;
using Mutagen.Bethesda.Plugins.Records;
using Mutagen.Bethesda.Plugins.Records.Internals;
using Mutagen.Bethesda.Plugins.Records.Mapping;
using Mutagen.Bethesda.Translations.Binary;
using Noggog;
using Noggog.StructuredStrings;
using Noggog.StructuredStrings.CSharp;
using RecordTypeInts = Mutagen.Bethesda.Fallout4.Internals.RecordTypeInts;
using RecordTypes = Mutagen.Bethesda.Fallout4.Internals.RecordTypes;
using System.Buffers.Binary;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Reactive.Disposables;
using System.Reactive.Linq;
#endregion

#nullable enable
namespace Mutagen.Bethesda.Fallout4
{
    #region Class
    public partial class PlacedObjectSpline :
        IEquatable<IPlacedObjectSplineGetter>,
        ILoquiObjectSetter<PlacedObjectSpline>,
        IPlacedObjectSpline
    {
        #region Ctor
        public PlacedObjectSpline()
        {
            CustomCtor();
        }
        partial void CustomCtor();
        #endregion

        #region Versioning
        public PlacedObjectSpline.VersioningBreaks Versioning { get; set; } = default(PlacedObjectSpline.VersioningBreaks);
        #endregion
        #region Slack
        public Single Slack { get; set; } = default(Single);
        #endregion
        #region Thickness
        public Single Thickness { get; set; } = default(Single);
        #endregion
        #region HalfExtents
        public P3Float HalfExtents { get; set; } = default(P3Float);
        #endregion
        #region IsWindDetachedEnd
        public Boolean IsWindDetachedEnd { get; set; } = default(Boolean);
        #endregion
        #region Unknown
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        private MemorySlice<Byte> _Unknown = new byte[0];
        public MemorySlice<Byte> Unknown
        {
            get => _Unknown;
            set => this._Unknown = value;
        }
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        ReadOnlyMemorySlice<Byte> IPlacedObjectSplineGetter.Unknown => this.Unknown;
        #endregion

        #region To String

        public void Print(
            StructuredStringBuilder sb,
            string? name = null)
        {
            PlacedObjectSplineMixIn.Print(
                item: this,
                sb: sb,
                name: name);
        }

        #endregion

        #region Equals and Hash
        public override bool Equals(object? obj)
        {
            if (obj is not IPlacedObjectSplineGetter rhs) return false;
            return ((PlacedObjectSplineCommon)((IPlacedObjectSplineGetter)this).CommonInstance()!).Equals(this, rhs, equalsMask: null);
        }

        public bool Equals(IPlacedObjectSplineGetter? obj)
        {
            return ((PlacedObjectSplineCommon)((IPlacedObjectSplineGetter)this).CommonInstance()!).Equals(this, obj, equalsMask: null);
        }

        public override int GetHashCode() => ((PlacedObjectSplineCommon)((IPlacedObjectSplineGetter)this).CommonInstance()!).GetHashCode(this);

        #endregion

        #region Mask
        public class Mask<TItem> :
            IEquatable<Mask<TItem>>,
            IMask<TItem>
        {
            #region Ctors
            public Mask(TItem initialValue)
            {
                this.Versioning = initialValue;
                this.Slack = initialValue;
                this.Thickness = initialValue;
                this.HalfExtents = initialValue;
                this.IsWindDetachedEnd = initialValue;
                this.Unknown = initialValue;
            }

            public Mask(
                TItem Versioning,
                TItem Slack,
                TItem Thickness,
                TItem HalfExtents,
                TItem IsWindDetachedEnd,
                TItem Unknown)
            {
                this.Versioning = Versioning;
                this.Slack = Slack;
                this.Thickness = Thickness;
                this.HalfExtents = HalfExtents;
                this.IsWindDetachedEnd = IsWindDetachedEnd;
                this.Unknown = Unknown;
            }

            #pragma warning disable CS8618
            protected Mask()
            {
            }
            #pragma warning restore CS8618

            #endregion

            #region Members
            public TItem Versioning;
            public TItem Slack;
            public TItem Thickness;
            public TItem HalfExtents;
            public TItem IsWindDetachedEnd;
            public TItem Unknown;
            #endregion

            #region Equals
            public override bool Equals(object? obj)
            {
                if (!(obj is Mask<TItem> rhs)) return false;
                return Equals(rhs);
            }

            public bool Equals(Mask<TItem>? rhs)
            {
                if (rhs == null) return false;
                if (!object.Equals(this.Versioning, rhs.Versioning)) return false;
                if (!object.Equals(this.Slack, rhs.Slack)) return false;
                if (!object.Equals(this.Thickness, rhs.Thickness)) return false;
                if (!object.Equals(this.HalfExtents, rhs.HalfExtents)) return false;
                if (!object.Equals(this.IsWindDetachedEnd, rhs.IsWindDetachedEnd)) return false;
                if (!object.Equals(this.Unknown, rhs.Unknown)) return false;
                return true;
            }
            public override int GetHashCode()
            {
                var hash = new HashCode();
                hash.Add(this.Versioning);
                hash.Add(this.Slack);
                hash.Add(this.Thickness);
                hash.Add(this.HalfExtents);
                hash.Add(this.IsWindDetachedEnd);
                hash.Add(this.Unknown);
                return hash.ToHashCode();
            }

            #endregion

            #region All
            public bool All(Func<TItem, bool> eval)
            {
                if (!eval(this.Versioning)) return false;
                if (!eval(this.Slack)) return false;
                if (!eval(this.Thickness)) return false;
                if (!eval(this.HalfExtents)) return false;
                if (!eval(this.IsWindDetachedEnd)) return false;
                if (!eval(this.Unknown)) return false;
                return true;
            }
            #endregion

            #region Any
            public bool Any(Func<TItem, bool> eval)
            {
                if (eval(this.Versioning)) return true;
                if (eval(this.Slack)) return true;
                if (eval(this.Thickness)) return true;
                if (eval(this.HalfExtents)) return true;
                if (eval(this.IsWindDetachedEnd)) return true;
                if (eval(this.Unknown)) return true;
                return false;
            }
            #endregion

            #region Translate
            public Mask<R> Translate<R>(Func<TItem, R> eval)
            {
                var ret = new PlacedObjectSpline.Mask<R>();
                this.Translate_InternalFill(ret, eval);
                return ret;
            }

            protected void Translate_InternalFill<R>(Mask<R> obj, Func<TItem, R> eval)
            {
                obj.Versioning = eval(this.Versioning);
                obj.Slack = eval(this.Slack);
                obj.Thickness = eval(this.Thickness);
                obj.HalfExtents = eval(this.HalfExtents);
                obj.IsWindDetachedEnd = eval(this.IsWindDetachedEnd);
                obj.Unknown = eval(this.Unknown);
            }
            #endregion

            #region To String
            public override string ToString() => this.Print();

            public string Print(PlacedObjectSpline.Mask<bool>? printMask = null)
            {
                var sb = new StructuredStringBuilder();
                Print(sb, printMask);
                return sb.ToString();
            }

            public void Print(StructuredStringBuilder sb, PlacedObjectSpline.Mask<bool>? printMask = null)
            {
                sb.AppendLine($"{nameof(PlacedObjectSpline.Mask<TItem>)} =>");
                using (sb.Brace())
                {
                    if (printMask?.Versioning ?? true)
                    {
                        sb.AppendItem(Versioning, "Versioning");
                    }
                    if (printMask?.Slack ?? true)
                    {
                        sb.AppendItem(Slack, "Slack");
                    }
                    if (printMask?.Thickness ?? true)
                    {
                        sb.AppendItem(Thickness, "Thickness");
                    }
                    if (printMask?.HalfExtents ?? true)
                    {
                        sb.AppendItem(HalfExtents, "HalfExtents");
                    }
                    if (printMask?.IsWindDetachedEnd ?? true)
                    {
                        sb.AppendItem(IsWindDetachedEnd, "IsWindDetachedEnd");
                    }
                    if (printMask?.Unknown ?? true)
                    {
                        sb.AppendItem(Unknown, "Unknown");
                    }
                }
            }
            #endregion

        }

        public class ErrorMask :
            IErrorMask,
            IErrorMask<ErrorMask>
        {
            #region Members
            public Exception? Overall { get; set; }
            private List<string>? _warnings;
            public List<string> Warnings
            {
                get
                {
                    if (_warnings == null)
                    {
                        _warnings = new List<string>();
                    }
                    return _warnings;
                }
            }
            public Exception? Versioning;
            public Exception? Slack;
            public Exception? Thickness;
            public Exception? HalfExtents;
            public Exception? IsWindDetachedEnd;
            public Exception? Unknown;
            #endregion

            #region IErrorMask
            public object? GetNthMask(int index)
            {
                PlacedObjectSpline_FieldIndex enu = (PlacedObjectSpline_FieldIndex)index;
                switch (enu)
                {
                    case PlacedObjectSpline_FieldIndex.Versioning:
                        return Versioning;
                    case PlacedObjectSpline_FieldIndex.Slack:
                        return Slack;
                    case PlacedObjectSpline_FieldIndex.Thickness:
                        return Thickness;
                    case PlacedObjectSpline_FieldIndex.HalfExtents:
                        return HalfExtents;
                    case PlacedObjectSpline_FieldIndex.IsWindDetachedEnd:
                        return IsWindDetachedEnd;
                    case PlacedObjectSpline_FieldIndex.Unknown:
                        return Unknown;
                    default:
                        throw new ArgumentException($"Index is out of range: {index}");
                }
            }

            public void SetNthException(int index, Exception ex)
            {
                PlacedObjectSpline_FieldIndex enu = (PlacedObjectSpline_FieldIndex)index;
                switch (enu)
                {
                    case PlacedObjectSpline_FieldIndex.Versioning:
                        this.Versioning = ex;
                        break;
                    case PlacedObjectSpline_FieldIndex.Slack:
                        this.Slack = ex;
                        break;
                    case PlacedObjectSpline_FieldIndex.Thickness:
                        this.Thickness = ex;
                        break;
                    case PlacedObjectSpline_FieldIndex.HalfExtents:
                        this.HalfExtents = ex;
                        break;
                    case PlacedObjectSpline_FieldIndex.IsWindDetachedEnd:
                        this.IsWindDetachedEnd = ex;
                        break;
                    case PlacedObjectSpline_FieldIndex.Unknown:
                        this.Unknown = ex;
                        break;
                    default:
                        throw new ArgumentException($"Index is out of range: {index}");
                }
            }

            public void SetNthMask(int index, object obj)
            {
                PlacedObjectSpline_FieldIndex enu = (PlacedObjectSpline_FieldIndex)index;
                switch (enu)
                {
                    case PlacedObjectSpline_FieldIndex.Versioning:
                        this.Versioning = (Exception?)obj;
                        break;
                    case PlacedObjectSpline_FieldIndex.Slack:
                        this.Slack = (Exception?)obj;
                        break;
                    case PlacedObjectSpline_FieldIndex.Thickness:
                        this.Thickness = (Exception?)obj;
                        break;
                    case PlacedObjectSpline_FieldIndex.HalfExtents:
                        this.HalfExtents = (Exception?)obj;
                        break;
                    case PlacedObjectSpline_FieldIndex.IsWindDetachedEnd:
                        this.IsWindDetachedEnd = (Exception?)obj;
                        break;
                    case PlacedObjectSpline_FieldIndex.Unknown:
                        this.Unknown = (Exception?)obj;
                        break;
                    default:
                        throw new ArgumentException($"Index is out of range: {index}");
                }
            }

            public bool IsInError()
            {
                if (Overall != null) return true;
                if (Versioning != null) return true;
                if (Slack != null) return true;
                if (Thickness != null) return true;
                if (HalfExtents != null) return true;
                if (IsWindDetachedEnd != null) return true;
                if (Unknown != null) return true;
                return false;
            }
            #endregion

            #region To String
            public override string ToString() => this.Print();

            public void Print(StructuredStringBuilder sb, string? name = null)
            {
                sb.AppendLine($"{(name ?? "ErrorMask")} =>");
                using (sb.Brace())
                {
                    if (this.Overall != null)
                    {
                        sb.AppendLine("Overall =>");
                        using (sb.Brace())
                        {
                            sb.AppendLine($"{this.Overall}");
                        }
                    }
                    PrintFillInternal(sb);
                }
            }
            protected void PrintFillInternal(StructuredStringBuilder sb)
            {
                {
                    sb.AppendItem(Versioning, "Versioning");
                }
                {
                    sb.AppendItem(Slack, "Slack");
                }
                {
                    sb.AppendItem(Thickness, "Thickness");
                }
                {
                    sb.AppendItem(HalfExtents, "HalfExtents");
                }
                {
                    sb.AppendItem(IsWindDetachedEnd, "IsWindDetachedEnd");
                }
                {
                    sb.AppendItem(Unknown, "Unknown");
                }
            }
            #endregion

            #region Combine
            public ErrorMask Combine(ErrorMask? rhs)
            {
                if (rhs == null) return this;
                var ret = new ErrorMask();
                ret.Versioning = this.Versioning.Combine(rhs.Versioning);
                ret.Slack = this.Slack.Combine(rhs.Slack);
                ret.Thickness = this.Thickness.Combine(rhs.Thickness);
                ret.HalfExtents = this.HalfExtents.Combine(rhs.HalfExtents);
                ret.IsWindDetachedEnd = this.IsWindDetachedEnd.Combine(rhs.IsWindDetachedEnd);
                ret.Unknown = this.Unknown.Combine(rhs.Unknown);
                return ret;
            }
            public static ErrorMask? Combine(ErrorMask? lhs, ErrorMask? rhs)
            {
                if (lhs != null && rhs != null) return lhs.Combine(rhs);
                return lhs ?? rhs;
            }
            #endregion

            #region Factory
            public static ErrorMask Factory(ErrorMaskBuilder errorMask)
            {
                return new ErrorMask();
            }
            #endregion

        }
        public class TranslationMask : ITranslationMask
        {
            #region Members
            private TranslationCrystal? _crystal;
            public readonly bool DefaultOn;
            public bool OnOverall;
            public bool Versioning;
            public bool Slack;
            public bool Thickness;
            public bool HalfExtents;
            public bool IsWindDetachedEnd;
            public bool Unknown;
            #endregion

            #region Ctors
            public TranslationMask(
                bool defaultOn,
                bool onOverall = true)
            {
                this.DefaultOn = defaultOn;
                this.OnOverall = onOverall;
                this.Versioning = defaultOn;
                this.Slack = defaultOn;
                this.Thickness = defaultOn;
                this.HalfExtents = defaultOn;
                this.IsWindDetachedEnd = defaultOn;
                this.Unknown = defaultOn;
            }

            #endregion

            public TranslationCrystal GetCrystal()
            {
                if (_crystal != null) return _crystal;
                var ret = new List<(bool On, TranslationCrystal? SubCrystal)>();
                GetCrystal(ret);
                _crystal = new TranslationCrystal(ret.ToArray());
                return _crystal;
            }

            protected void GetCrystal(List<(bool On, TranslationCrystal? SubCrystal)> ret)
            {
                ret.Add((Versioning, null));
                ret.Add((Slack, null));
                ret.Add((Thickness, null));
                ret.Add((HalfExtents, null));
                ret.Add((IsWindDetachedEnd, null));
                ret.Add((Unknown, null));
            }

            public static implicit operator TranslationMask(bool defaultOn)
            {
                return new TranslationMask(defaultOn: defaultOn, onOverall: defaultOn);
            }

        }
        #endregion

        #region Mutagen
        [Flags]
        public enum VersioningBreaks
        {
            Break0 = 1
        }
        #endregion

        #region Binary Translation
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        protected object BinaryWriteTranslator => PlacedObjectSplineBinaryWriteTranslation.Instance;
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        object IBinaryItem.BinaryWriteTranslator => this.BinaryWriteTranslator;
        void IBinaryItem.WriteToBinary(
            MutagenWriter writer,
            TypedWriteParams translationParams = default)
        {
            ((PlacedObjectSplineBinaryWriteTranslation)this.BinaryWriteTranslator).Write(
                item: this,
                writer: writer,
                translationParams: translationParams);
        }
        #region Binary Create
        public static PlacedObjectSpline CreateFromBinary(
            MutagenFrame frame,
            TypedParseParams translationParams = default)
        {
            var ret = new PlacedObjectSpline();
            ((PlacedObjectSplineSetterCommon)((IPlacedObjectSplineGetter)ret).CommonSetterInstance()!).CopyInFromBinary(
                item: ret,
                frame: frame,
                translationParams: translationParams);
            return ret;
        }

        #endregion

        public static bool TryCreateFromBinary(
            MutagenFrame frame,
            out PlacedObjectSpline item,
            TypedParseParams translationParams = default)
        {
            var startPos = frame.Position;
            item = CreateFromBinary(
                frame: frame,
                translationParams: translationParams);
            return startPos != frame.Position;
        }
        #endregion

        void IPrintable.Print(StructuredStringBuilder sb, string? name) => this.Print(sb, name);

        void IClearable.Clear()
        {
            ((PlacedObjectSplineSetterCommon)((IPlacedObjectSplineGetter)this).CommonSetterInstance()!).Clear(this);
        }

        internal static PlacedObjectSpline GetNew()
        {
            return new PlacedObjectSpline();
        }

    }
    #endregion

    #region Interface
    public partial interface IPlacedObjectSpline :
        ILoquiObjectSetter<IPlacedObjectSpline>,
        IPlacedObjectSplineGetter
    {
        new PlacedObjectSpline.VersioningBreaks Versioning { get; set; }
        new Single Slack { get; set; }
        new Single Thickness { get; set; }
        new P3Float HalfExtents { get; set; }
        new Boolean IsWindDetachedEnd { get; set; }
        new MemorySlice<Byte> Unknown { get; set; }
    }

    public partial interface IPlacedObjectSplineGetter :
        ILoquiObject,
        IBinaryItem,
        ILoquiObject<IPlacedObjectSplineGetter>
    {
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        object CommonInstance();
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        object? CommonSetterInstance();
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        object CommonSetterTranslationInstance();
        static ILoquiRegistration StaticRegistration => PlacedObjectSpline_Registration.Instance;
        PlacedObjectSpline.VersioningBreaks Versioning { get; }
        Single Slack { get; }
        Single Thickness { get; }
        P3Float HalfExtents { get; }
        Boolean IsWindDetachedEnd { get; }
        ReadOnlyMemorySlice<Byte> Unknown { get; }

    }

    #endregion

    #region Common MixIn
    public static partial class PlacedObjectSplineMixIn
    {
        public static void Clear(this IPlacedObjectSpline item)
        {
            ((PlacedObjectSplineSetterCommon)((IPlacedObjectSplineGetter)item).CommonSetterInstance()!).Clear(item: item);
        }

        public static PlacedObjectSpline.Mask<bool> GetEqualsMask(
            this IPlacedObjectSplineGetter item,
            IPlacedObjectSplineGetter rhs,
            EqualsMaskHelper.Include include = EqualsMaskHelper.Include.All)
        {
            return ((PlacedObjectSplineCommon)((IPlacedObjectSplineGetter)item).CommonInstance()!).GetEqualsMask(
                item: item,
                rhs: rhs,
                include: include);
        }

        public static string Print(
            this IPlacedObjectSplineGetter item,
            string? name = null,
            PlacedObjectSpline.Mask<bool>? printMask = null)
        {
            return ((PlacedObjectSplineCommon)((IPlacedObjectSplineGetter)item).CommonInstance()!).Print(
                item: item,
                name: name,
                printMask: printMask);
        }

        public static void Print(
            this IPlacedObjectSplineGetter item,
            StructuredStringBuilder sb,
            string? name = null,
            PlacedObjectSpline.Mask<bool>? printMask = null)
        {
            ((PlacedObjectSplineCommon)((IPlacedObjectSplineGetter)item).CommonInstance()!).Print(
                item: item,
                sb: sb,
                name: name,
                printMask: printMask);
        }

        public static bool Equals(
            this IPlacedObjectSplineGetter item,
            IPlacedObjectSplineGetter rhs,
            PlacedObjectSpline.TranslationMask? equalsMask = null)
        {
            return ((PlacedObjectSplineCommon)((IPlacedObjectSplineGetter)item).CommonInstance()!).Equals(
                lhs: item,
                rhs: rhs,
                equalsMask: equalsMask?.GetCrystal());
        }

        public static void DeepCopyIn(
            this IPlacedObjectSpline lhs,
            IPlacedObjectSplineGetter rhs)
        {
            ((PlacedObjectSplineSetterTranslationCommon)((IPlacedObjectSplineGetter)lhs).CommonSetterTranslationInstance()!).DeepCopyIn(
                item: lhs,
                rhs: rhs,
                errorMask: default,
                copyMask: default,
                deepCopy: false);
        }

        public static void DeepCopyIn(
            this IPlacedObjectSpline lhs,
            IPlacedObjectSplineGetter rhs,
            PlacedObjectSpline.TranslationMask? copyMask = null)
        {
            ((PlacedObjectSplineSetterTranslationCommon)((IPlacedObjectSplineGetter)lhs).CommonSetterTranslationInstance()!).DeepCopyIn(
                item: lhs,
                rhs: rhs,
                errorMask: default,
                copyMask: copyMask?.GetCrystal(),
                deepCopy: false);
        }

        public static void DeepCopyIn(
            this IPlacedObjectSpline lhs,
            IPlacedObjectSplineGetter rhs,
            out PlacedObjectSpline.ErrorMask errorMask,
            PlacedObjectSpline.TranslationMask? copyMask = null)
        {
            var errorMaskBuilder = new ErrorMaskBuilder();
            ((PlacedObjectSplineSetterTranslationCommon)((IPlacedObjectSplineGetter)lhs).CommonSetterTranslationInstance()!).DeepCopyIn(
                item: lhs,
                rhs: rhs,
                errorMask: errorMaskBuilder,
                copyMask: copyMask?.GetCrystal(),
                deepCopy: false);
            errorMask = PlacedObjectSpline.ErrorMask.Factory(errorMaskBuilder);
        }

        public static void DeepCopyIn(
            this IPlacedObjectSpline lhs,
            IPlacedObjectSplineGetter rhs,
            ErrorMaskBuilder? errorMask,
            TranslationCrystal? copyMask)
        {
            ((PlacedObjectSplineSetterTranslationCommon)((IPlacedObjectSplineGetter)lhs).CommonSetterTranslationInstance()!).DeepCopyIn(
                item: lhs,
                rhs: rhs,
                errorMask: errorMask,
                copyMask: copyMask,
                deepCopy: false);
        }

        public static PlacedObjectSpline DeepCopy(
            this IPlacedObjectSplineGetter item,
            PlacedObjectSpline.TranslationMask? copyMask = null)
        {
            return ((PlacedObjectSplineSetterTranslationCommon)((IPlacedObjectSplineGetter)item).CommonSetterTranslationInstance()!).DeepCopy(
                item: item,
                copyMask: copyMask);
        }

        public static PlacedObjectSpline DeepCopy(
            this IPlacedObjectSplineGetter item,
            out PlacedObjectSpline.ErrorMask errorMask,
            PlacedObjectSpline.TranslationMask? copyMask = null)
        {
            return ((PlacedObjectSplineSetterTranslationCommon)((IPlacedObjectSplineGetter)item).CommonSetterTranslationInstance()!).DeepCopy(
                item: item,
                copyMask: copyMask,
                errorMask: out errorMask);
        }

        public static PlacedObjectSpline DeepCopy(
            this IPlacedObjectSplineGetter item,
            ErrorMaskBuilder? errorMask,
            TranslationCrystal? copyMask = null)
        {
            return ((PlacedObjectSplineSetterTranslationCommon)((IPlacedObjectSplineGetter)item).CommonSetterTranslationInstance()!).DeepCopy(
                item: item,
                copyMask: copyMask,
                errorMask: errorMask);
        }

        #region Binary Translation
        public static void CopyInFromBinary(
            this IPlacedObjectSpline item,
            MutagenFrame frame,
            TypedParseParams translationParams = default)
        {
            ((PlacedObjectSplineSetterCommon)((IPlacedObjectSplineGetter)item).CommonSetterInstance()!).CopyInFromBinary(
                item: item,
                frame: frame,
                translationParams: translationParams);
        }

        #endregion

    }
    #endregion

}

namespace Mutagen.Bethesda.Fallout4
{
    #region Field Index
    internal enum PlacedObjectSpline_FieldIndex
    {
        Versioning = 0,
        Slack = 1,
        Thickness = 2,
        HalfExtents = 3,
        IsWindDetachedEnd = 4,
        Unknown = 5,
    }
    #endregion

    #region Registration
    internal partial class PlacedObjectSpline_Registration : ILoquiRegistration
    {
        public static readonly PlacedObjectSpline_Registration Instance = new PlacedObjectSpline_Registration();

        public static ProtocolKey ProtocolKey => ProtocolDefinition_Fallout4.ProtocolKey;

        public const ushort AdditionalFieldCount = 6;

        public const ushort FieldCount = 6;

        public static readonly Type MaskType = typeof(PlacedObjectSpline.Mask<>);

        public static readonly Type ErrorMaskType = typeof(PlacedObjectSpline.ErrorMask);

        public static readonly Type ClassType = typeof(PlacedObjectSpline);

        public static readonly Type GetterType = typeof(IPlacedObjectSplineGetter);

        public static readonly Type? InternalGetterType = null;

        public static readonly Type SetterType = typeof(IPlacedObjectSpline);

        public static readonly Type? InternalSetterType = null;

        public const string FullName = "Mutagen.Bethesda.Fallout4.PlacedObjectSpline";

        public const string Name = "PlacedObjectSpline";

        public const string Namespace = "Mutagen.Bethesda.Fallout4";

        public const byte GenericCount = 0;

        public static readonly Type? GenericRegistrationType = null;

        public static readonly RecordType TriggeringRecordType = RecordTypes.XBSD;
        public static RecordTriggerSpecs TriggerSpecs => _recordSpecs.Value;
        private static readonly Lazy<RecordTriggerSpecs> _recordSpecs = new Lazy<RecordTriggerSpecs>(() =>
        {
            var all = RecordCollection.Factory(RecordTypes.XBSD);
            return new RecordTriggerSpecs(allRecordTypes: all);
        });
        public static readonly Type BinaryWriteTranslation = typeof(PlacedObjectSplineBinaryWriteTranslation);
        #region Interface
        ProtocolKey ILoquiRegistration.ProtocolKey => ProtocolKey;
        ushort ILoquiRegistration.FieldCount => FieldCount;
        ushort ILoquiRegistration.AdditionalFieldCount => AdditionalFieldCount;
        Type ILoquiRegistration.MaskType => MaskType;
        Type ILoquiRegistration.ErrorMaskType => ErrorMaskType;
        Type ILoquiRegistration.ClassType => ClassType;
        Type ILoquiRegistration.SetterType => SetterType;
        Type? ILoquiRegistration.InternalSetterType => InternalSetterType;
        Type ILoquiRegistration.GetterType => GetterType;
        Type? ILoquiRegistration.InternalGetterType => InternalGetterType;
        string ILoquiRegistration.FullName => FullName;
        string ILoquiRegistration.Name => Name;
        string ILoquiRegistration.Namespace => Namespace;
        byte ILoquiRegistration.GenericCount => GenericCount;
        Type? ILoquiRegistration.GenericRegistrationType => GenericRegistrationType;
        ushort? ILoquiRegistration.GetNameIndex(StringCaseAgnostic name) => throw new NotImplementedException();
        bool ILoquiRegistration.GetNthIsEnumerable(ushort index) => throw new NotImplementedException();
        bool ILoquiRegistration.GetNthIsLoqui(ushort index) => throw new NotImplementedException();
        bool ILoquiRegistration.GetNthIsSingleton(ushort index) => throw new NotImplementedException();
        string ILoquiRegistration.GetNthName(ushort index) => throw new NotImplementedException();
        bool ILoquiRegistration.IsNthDerivative(ushort index) => throw new NotImplementedException();
        bool ILoquiRegistration.IsProtected(ushort index) => throw new NotImplementedException();
        Type ILoquiRegistration.GetNthType(ushort index) => throw new NotImplementedException();
        #endregion

    }
    #endregion

    #region Common
    internal partial class PlacedObjectSplineSetterCommon
    {
        public static readonly PlacedObjectSplineSetterCommon Instance = new PlacedObjectSplineSetterCommon();

        partial void ClearPartial();
        
        public void Clear(IPlacedObjectSpline item)
        {
            ClearPartial();
            item.Versioning = default(PlacedObjectSpline.VersioningBreaks);
            item.Slack = default(Single);
            item.Thickness = default(Single);
            item.HalfExtents = default(P3Float);
            item.IsWindDetachedEnd = default(Boolean);
            item.Unknown = Array.Empty<byte>();
        }
        
        #region Mutagen
        public void RemapLinks(IPlacedObjectSpline obj, IReadOnlyDictionary<FormKey, FormKey> mapping)
        {
        }
        
        #endregion
        
        #region Binary Translation
        public virtual void CopyInFromBinary(
            IPlacedObjectSpline item,
            MutagenFrame frame,
            TypedParseParams translationParams)
        {
            frame = frame.SpawnWithFinalPosition(HeaderTranslation.ParseSubrecord(
                frame.Reader,
                translationParams.ConvertToCustom(RecordTypes.XBSD),
                translationParams.LengthOverride));
            PluginUtilityTranslation.SubrecordParse(
                record: item,
                frame: frame,
                translationParams: translationParams,
                fillStructs: PlacedObjectSplineBinaryCreateTranslation.FillBinaryStructs);
        }
        
        #endregion
        
    }
    internal partial class PlacedObjectSplineCommon
    {
        public static readonly PlacedObjectSplineCommon Instance = new PlacedObjectSplineCommon();

        public PlacedObjectSpline.Mask<bool> GetEqualsMask(
            IPlacedObjectSplineGetter item,
            IPlacedObjectSplineGetter rhs,
            EqualsMaskHelper.Include include = EqualsMaskHelper.Include.All)
        {
            var ret = new PlacedObjectSpline.Mask<bool>(false);
            ((PlacedObjectSplineCommon)((IPlacedObjectSplineGetter)item).CommonInstance()!).FillEqualsMask(
                item: item,
                rhs: rhs,
                ret: ret,
                include: include);
            return ret;
        }
        
        public void FillEqualsMask(
            IPlacedObjectSplineGetter item,
            IPlacedObjectSplineGetter rhs,
            PlacedObjectSpline.Mask<bool> ret,
            EqualsMaskHelper.Include include = EqualsMaskHelper.Include.All)
        {
            ret.Versioning = item.Versioning == rhs.Versioning;
            ret.Slack = item.Slack.EqualsWithin(rhs.Slack);
            ret.Thickness = item.Thickness.EqualsWithin(rhs.Thickness);
            ret.HalfExtents = item.HalfExtents.Equals(rhs.HalfExtents);
            ret.IsWindDetachedEnd = item.IsWindDetachedEnd == rhs.IsWindDetachedEnd;
            ret.Unknown = MemoryExtensions.SequenceEqual(item.Unknown.Span, rhs.Unknown.Span);
        }
        
        public string Print(
            IPlacedObjectSplineGetter item,
            string? name = null,
            PlacedObjectSpline.Mask<bool>? printMask = null)
        {
            var sb = new StructuredStringBuilder();
            Print(
                item: item,
                sb: sb,
                name: name,
                printMask: printMask);
            return sb.ToString();
        }
        
        public void Print(
            IPlacedObjectSplineGetter item,
            StructuredStringBuilder sb,
            string? name = null,
            PlacedObjectSpline.Mask<bool>? printMask = null)
        {
            if (name == null)
            {
                sb.AppendLine($"PlacedObjectSpline =>");
            }
            else
            {
                sb.AppendLine($"{name} (PlacedObjectSpline) =>");
            }
            using (sb.Brace())
            {
                ToStringFields(
                    item: item,
                    sb: sb,
                    printMask: printMask);
            }
        }
        
        protected static void ToStringFields(
            IPlacedObjectSplineGetter item,
            StructuredStringBuilder sb,
            PlacedObjectSpline.Mask<bool>? printMask = null)
        {
            if (printMask?.Versioning ?? true)
            {
                sb.AppendItem(item.Versioning, "Versioning");
            }
            if (printMask?.Slack ?? true)
            {
                sb.AppendItem(item.Slack, "Slack");
            }
            if (printMask?.Thickness ?? true)
            {
                sb.AppendItem(item.Thickness, "Thickness");
            }
            if (printMask?.HalfExtents ?? true)
            {
                sb.AppendItem(item.HalfExtents, "HalfExtents");
            }
            if (printMask?.IsWindDetachedEnd ?? true)
            {
                sb.AppendItem(item.IsWindDetachedEnd, "IsWindDetachedEnd");
            }
            if (printMask?.Unknown ?? true)
            {
                sb.AppendLine($"Unknown => {SpanExt.ToHexString(item.Unknown)}");
            }
        }
        
        #region Equals and Hash
        public virtual bool Equals(
            IPlacedObjectSplineGetter? lhs,
            IPlacedObjectSplineGetter? rhs,
            TranslationCrystal? equalsMask)
        {
            if (!EqualsMaskHelper.RefEquality(lhs, rhs, out var isEqual)) return isEqual;
            if ((equalsMask?.GetShouldTranslate((int)PlacedObjectSpline_FieldIndex.Versioning) ?? true))
            {
                if (lhs.Versioning != rhs.Versioning) return false;
            }
            if ((equalsMask?.GetShouldTranslate((int)PlacedObjectSpline_FieldIndex.Slack) ?? true))
            {
                if (!lhs.Slack.EqualsWithin(rhs.Slack)) return false;
            }
            if ((equalsMask?.GetShouldTranslate((int)PlacedObjectSpline_FieldIndex.Thickness) ?? true))
            {
                if (!lhs.Thickness.EqualsWithin(rhs.Thickness)) return false;
            }
            if ((equalsMask?.GetShouldTranslate((int)PlacedObjectSpline_FieldIndex.HalfExtents) ?? true))
            {
                if (!lhs.HalfExtents.Equals(rhs.HalfExtents)) return false;
            }
            if ((equalsMask?.GetShouldTranslate((int)PlacedObjectSpline_FieldIndex.IsWindDetachedEnd) ?? true))
            {
                if (lhs.IsWindDetachedEnd != rhs.IsWindDetachedEnd) return false;
            }
            if ((equalsMask?.GetShouldTranslate((int)PlacedObjectSpline_FieldIndex.Unknown) ?? true))
            {
                if (!MemoryExtensions.SequenceEqual(lhs.Unknown.Span, rhs.Unknown.Span)) return false;
            }
            return true;
        }
        
        public virtual int GetHashCode(IPlacedObjectSplineGetter item)
        {
            var hash = new HashCode();
            hash.Add(item.Versioning);
            hash.Add(item.Slack);
            hash.Add(item.Thickness);
            hash.Add(item.HalfExtents);
            hash.Add(item.IsWindDetachedEnd);
            hash.Add(item.Unknown);
            return hash.ToHashCode();
        }
        
        #endregion
        
        
        public object GetNew()
        {
            return PlacedObjectSpline.GetNew();
        }
        
        #region Mutagen
        public IEnumerable<IFormLinkGetter> EnumerateFormLinks(IPlacedObjectSplineGetter obj)
        {
            yield break;
        }
        
        #endregion
        
    }
    internal partial class PlacedObjectSplineSetterTranslationCommon
    {
        public static readonly PlacedObjectSplineSetterTranslationCommon Instance = new PlacedObjectSplineSetterTranslationCommon();

        #region DeepCopyIn
        public void DeepCopyIn(
            IPlacedObjectSpline item,
            IPlacedObjectSplineGetter rhs,
            ErrorMaskBuilder? errorMask,
            TranslationCrystal? copyMask,
            bool deepCopy)
        {
            if ((copyMask?.GetShouldTranslate((int)PlacedObjectSpline_FieldIndex.Versioning) ?? true))
            {
                item.Versioning = rhs.Versioning;
            }
            if ((copyMask?.GetShouldTranslate((int)PlacedObjectSpline_FieldIndex.Slack) ?? true))
            {
                item.Slack = rhs.Slack;
            }
            if ((copyMask?.GetShouldTranslate((int)PlacedObjectSpline_FieldIndex.Thickness) ?? true))
            {
                item.Thickness = rhs.Thickness;
            }
            if ((copyMask?.GetShouldTranslate((int)PlacedObjectSpline_FieldIndex.HalfExtents) ?? true))
            {
                item.HalfExtents = rhs.HalfExtents;
            }
            if (rhs.Versioning.HasFlag(PlacedObjectSpline.VersioningBreaks.Break0)) return;
            if ((copyMask?.GetShouldTranslate((int)PlacedObjectSpline_FieldIndex.IsWindDetachedEnd) ?? true))
            {
                item.IsWindDetachedEnd = rhs.IsWindDetachedEnd;
            }
            if ((copyMask?.GetShouldTranslate((int)PlacedObjectSpline_FieldIndex.Unknown) ?? true))
            {
                item.Unknown = rhs.Unknown.ToArray();
            }
        }
        
        #endregion
        
        public PlacedObjectSpline DeepCopy(
            IPlacedObjectSplineGetter item,
            PlacedObjectSpline.TranslationMask? copyMask = null)
        {
            PlacedObjectSpline ret = (PlacedObjectSpline)((PlacedObjectSplineCommon)((IPlacedObjectSplineGetter)item).CommonInstance()!).GetNew();
            ((PlacedObjectSplineSetterTranslationCommon)((IPlacedObjectSplineGetter)ret).CommonSetterTranslationInstance()!).DeepCopyIn(
                item: ret,
                rhs: item,
                errorMask: null,
                copyMask: copyMask?.GetCrystal(),
                deepCopy: true);
            return ret;
        }
        
        public PlacedObjectSpline DeepCopy(
            IPlacedObjectSplineGetter item,
            out PlacedObjectSpline.ErrorMask errorMask,
            PlacedObjectSpline.TranslationMask? copyMask = null)
        {
            var errorMaskBuilder = new ErrorMaskBuilder();
            PlacedObjectSpline ret = (PlacedObjectSpline)((PlacedObjectSplineCommon)((IPlacedObjectSplineGetter)item).CommonInstance()!).GetNew();
            ((PlacedObjectSplineSetterTranslationCommon)((IPlacedObjectSplineGetter)ret).CommonSetterTranslationInstance()!).DeepCopyIn(
                ret,
                item,
                errorMask: errorMaskBuilder,
                copyMask: copyMask?.GetCrystal(),
                deepCopy: true);
            errorMask = PlacedObjectSpline.ErrorMask.Factory(errorMaskBuilder);
            return ret;
        }
        
        public PlacedObjectSpline DeepCopy(
            IPlacedObjectSplineGetter item,
            ErrorMaskBuilder? errorMask,
            TranslationCrystal? copyMask = null)
        {
            PlacedObjectSpline ret = (PlacedObjectSpline)((PlacedObjectSplineCommon)((IPlacedObjectSplineGetter)item).CommonInstance()!).GetNew();
            ((PlacedObjectSplineSetterTranslationCommon)((IPlacedObjectSplineGetter)ret).CommonSetterTranslationInstance()!).DeepCopyIn(
                item: ret,
                rhs: item,
                errorMask: errorMask,
                copyMask: copyMask,
                deepCopy: true);
            return ret;
        }
        
    }
    #endregion

}

namespace Mutagen.Bethesda.Fallout4
{
    public partial class PlacedObjectSpline
    {
        #region Common Routing
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        ILoquiRegistration ILoquiObject.Registration => PlacedObjectSpline_Registration.Instance;
        public static ILoquiRegistration StaticRegistration => PlacedObjectSpline_Registration.Instance;
        [DebuggerStepThrough]
        protected object CommonInstance() => PlacedObjectSplineCommon.Instance;
        [DebuggerStepThrough]
        protected object CommonSetterInstance()
        {
            return PlacedObjectSplineSetterCommon.Instance;
        }
        [DebuggerStepThrough]
        protected object CommonSetterTranslationInstance() => PlacedObjectSplineSetterTranslationCommon.Instance;
        [DebuggerStepThrough]
        object IPlacedObjectSplineGetter.CommonInstance() => this.CommonInstance();
        [DebuggerStepThrough]
        object IPlacedObjectSplineGetter.CommonSetterInstance() => this.CommonSetterInstance();
        [DebuggerStepThrough]
        object IPlacedObjectSplineGetter.CommonSetterTranslationInstance() => this.CommonSetterTranslationInstance();

        #endregion

    }
}

#region Modules
#region Binary Translation
namespace Mutagen.Bethesda.Fallout4
{
    public partial class PlacedObjectSplineBinaryWriteTranslation : IBinaryWriteTranslator
    {
        public static readonly PlacedObjectSplineBinaryWriteTranslation Instance = new();

        public static void WriteEmbedded(
            IPlacedObjectSplineGetter item,
            MutagenWriter writer)
        {
            FloatBinaryTranslation<MutagenFrame, MutagenWriter>.Instance.Write(
                writer: writer,
                item: item.Slack);
            FloatBinaryTranslation<MutagenFrame, MutagenWriter>.Instance.Write(
                writer: writer,
                item: item.Thickness);
            P3FloatBinaryTranslation<MutagenFrame, MutagenWriter>.Instance.Write(
                writer: writer,
                item: item.HalfExtents);
            if (!item.Versioning.HasFlag(PlacedObjectSpline.VersioningBreaks.Break0))
            {
                writer.Write(item.IsWindDetachedEnd);
                ByteArrayBinaryTranslation<MutagenFrame, MutagenWriter>.Instance.Write(
                    writer: writer,
                    item: item.Unknown);
            }
        }

        public void Write(
            MutagenWriter writer,
            IPlacedObjectSplineGetter item,
            TypedWriteParams translationParams)
        {
            using (HeaderExport.Subrecord(
                writer: writer,
                record: translationParams.ConvertToCustom(RecordTypes.XBSD),
                overflowRecord: translationParams.OverflowRecordType,
                out var writerToUse))
            {
                WriteEmbedded(
                    item: item,
                    writer: writerToUse);
            }
        }

        public void Write(
            MutagenWriter writer,
            object item,
            TypedWriteParams translationParams = default)
        {
            Write(
                item: (IPlacedObjectSplineGetter)item,
                writer: writer,
                translationParams: translationParams);
        }

    }

    internal partial class PlacedObjectSplineBinaryCreateTranslation
    {
        public static readonly PlacedObjectSplineBinaryCreateTranslation Instance = new PlacedObjectSplineBinaryCreateTranslation();

        public static void FillBinaryStructs(
            IPlacedObjectSpline item,
            MutagenFrame frame)
        {
            item.Slack = FloatBinaryTranslation<MutagenFrame, MutagenWriter>.Instance.Parse(reader: frame);
            item.Thickness = FloatBinaryTranslation<MutagenFrame, MutagenWriter>.Instance.Parse(reader: frame);
            item.HalfExtents = P3FloatBinaryTranslation<MutagenFrame, MutagenWriter>.Instance.Parse(reader: frame);
            if (frame.Complete)
            {
                item.Versioning |= PlacedObjectSpline.VersioningBreaks.Break0;
                return;
            }
            item.IsWindDetachedEnd = frame.ReadBoolean();
            item.Unknown = ByteArrayBinaryTranslation<MutagenFrame, MutagenWriter>.Instance.Parse(reader: frame);
        }

    }

}
namespace Mutagen.Bethesda.Fallout4
{
    #region Binary Write Mixins
    public static class PlacedObjectSplineBinaryTranslationMixIn
    {
        public static void WriteToBinary(
            this IPlacedObjectSplineGetter item,
            MutagenWriter writer,
            TypedWriteParams translationParams = default)
        {
            ((PlacedObjectSplineBinaryWriteTranslation)item.BinaryWriteTranslator).Write(
                item: item,
                writer: writer,
                translationParams: translationParams);
        }

    }
    #endregion


}
namespace Mutagen.Bethesda.Fallout4
{
    internal partial class PlacedObjectSplineBinaryOverlay :
        PluginBinaryOverlay,
        IPlacedObjectSplineGetter
    {
        #region Common Routing
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        ILoquiRegistration ILoquiObject.Registration => PlacedObjectSpline_Registration.Instance;
        public static ILoquiRegistration StaticRegistration => PlacedObjectSpline_Registration.Instance;
        [DebuggerStepThrough]
        protected object CommonInstance() => PlacedObjectSplineCommon.Instance;
        [DebuggerStepThrough]
        protected object CommonSetterTranslationInstance() => PlacedObjectSplineSetterTranslationCommon.Instance;
        [DebuggerStepThrough]
        object IPlacedObjectSplineGetter.CommonInstance() => this.CommonInstance();
        [DebuggerStepThrough]
        object? IPlacedObjectSplineGetter.CommonSetterInstance() => null;
        [DebuggerStepThrough]
        object IPlacedObjectSplineGetter.CommonSetterTranslationInstance() => this.CommonSetterTranslationInstance();

        #endregion

        void IPrintable.Print(StructuredStringBuilder sb, string? name) => this.Print(sb, name);

        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        protected object BinaryWriteTranslator => PlacedObjectSplineBinaryWriteTranslation.Instance;
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        object IBinaryItem.BinaryWriteTranslator => this.BinaryWriteTranslator;
        void IBinaryItem.WriteToBinary(
            MutagenWriter writer,
            TypedWriteParams translationParams = default)
        {
            ((PlacedObjectSplineBinaryWriteTranslation)this.BinaryWriteTranslator).Write(
                item: this,
                writer: writer,
                translationParams: translationParams);
        }

        public PlacedObjectSpline.VersioningBreaks Versioning { get; private set; }
        public Single Slack => _structData.Slice(0x0, 0x4).Float();
        public Single Thickness => _structData.Slice(0x4, 0x4).Float();
        public P3Float HalfExtents => P3FloatBinaryTranslation<MutagenFrame, MutagenWriter>.Instance.Read(_structData.Slice(0x8, 0xC));
        public Boolean IsWindDetachedEnd => _structData.Length <= 0x14 ? default : _structData.Slice(0x14, 0x1)[0] >= 1;
        #region Unknown
        public ReadOnlyMemorySlice<Byte> Unknown => _structData.Span.Slice(0x15).ToArray();
        protected int UnknownEndingPos;
        #endregion
        partial void CustomFactoryEnd(
            OverlayStream stream,
            int finalPos,
            int offset);

        partial void CustomCtor();
        protected PlacedObjectSplineBinaryOverlay(
            MemoryPair memoryPair,
            BinaryOverlayFactoryPackage package)
            : base(
                memoryPair: memoryPair,
                package: package)
        {
            this.CustomCtor();
        }

        public static IPlacedObjectSplineGetter PlacedObjectSplineFactory(
            OverlayStream stream,
            BinaryOverlayFactoryPackage package,
            TypedParseParams translationParams = default)
        {
            stream = ExtractSubrecordStructMemory(
                stream: stream,
                meta: package.MetaData.Constants,
                translationParams: translationParams,
                memoryPair: out var memoryPair,
                offset: out var offset,
                finalPos: out var finalPos);
            var ret = new PlacedObjectSplineBinaryOverlay(
                memoryPair: memoryPair,
                package: package);
            if (ret._structData.Length <= 0x14)
            {
                ret.Versioning |= PlacedObjectSpline.VersioningBreaks.Break0;
            }
            ret.CustomFactoryEnd(
                stream: stream,
                finalPos: stream.Length,
                offset: offset);
            return ret;
        }

        public static IPlacedObjectSplineGetter PlacedObjectSplineFactory(
            ReadOnlyMemorySlice<byte> slice,
            BinaryOverlayFactoryPackage package,
            TypedParseParams translationParams = default)
        {
            return PlacedObjectSplineFactory(
                stream: new OverlayStream(slice, package),
                package: package,
                translationParams: translationParams);
        }

        #region To String

        public void Print(
            StructuredStringBuilder sb,
            string? name = null)
        {
            PlacedObjectSplineMixIn.Print(
                item: this,
                sb: sb,
                name: name);
        }

        #endregion

        #region Equals and Hash
        public override bool Equals(object? obj)
        {
            if (obj is not IPlacedObjectSplineGetter rhs) return false;
            return ((PlacedObjectSplineCommon)((IPlacedObjectSplineGetter)this).CommonInstance()!).Equals(this, rhs, equalsMask: null);
        }

        public bool Equals(IPlacedObjectSplineGetter? obj)
        {
            return ((PlacedObjectSplineCommon)((IPlacedObjectSplineGetter)this).CommonInstance()!).Equals(this, obj, equalsMask: null);
        }

        public override int GetHashCode() => ((PlacedObjectSplineCommon)((IPlacedObjectSplineGetter)this).CommonInstance()!).GetHashCode(this);

        #endregion

    }

}
#endregion

#endregion

