namespace Mutagen.Bethesda.Fallout3;

public partial class APerkEntryPointEffect
{
    public enum EntryType
    {
        CalculateWeaponDamage = 0,
        CalculateMyCriticalHitChance = 1,
        CalculateMyCriticalHitDamage = 2,
        CalculateWeaponAttackAPCost = 3,
        CalculateMineExplodeChance = 4,
        AdjustRangePenalty = 5,
        AdjustLimbDamage = 6,
        CalculateWeaponRange = 7,
        CalculateToHitChance = 8,
        AdjustExperiencePoints = 9,
        AdjustGainedSkillPoints = 10,
        AdjustBookSkillPoints = 11,
        ModifyRecoveredHealth = 12,
        CalculateInventoryAPCost = 13,
        GetDisposition = 14,
        GetShouldAttack = 15,
        GetShouldAssist = 16,
        CalculateBuyPrice = 17,
        GetBadKarma = 18,
        GetGoodKarma = 19,
        IgnoreLockedTerminal = 20,
        AddLeveledListOnDeath = 21,
        GetMaxCarryWeight = 22,
        ModifyAddictionChance = 23,
        ModifyAddictionDuration = 24,
        ModifyPositiveChemDuration = 25,
        AdjustDrinkingRadiation = 26,
        Activate = 27,
        MysteriousStranger = 28,
        HasParalyzingPalm = 29,
        HackingScienceBonus = 30,
        IgnoreRunningDuringDetection = 31,
        IgnoreBrokenLock = 32,
        HasConcentratedFire = 33,
        CalculateGunSpread = 34,
        PlayerKillAPReward = 35,
        ModifyEnemyCriticalHitChance = 36,
        // FNV-only entry points below
        ReloadSpeed = 37,
        EquipSpeed = 38,
        ActionPointRegen = 39,
        ActionPointCost = 40,
        MissFortune = 41,
        ModifyRunSpeed = 42,
        ModifyAttackSpeed = 43,
        ModifyRadiationConsumed = 44,
        HasPipHacker = 45,
        HasMeltdown = 46,
        SeeEnemyHealth = 47,
        HasJuryRigging = 48,
        ModifyThreatRange = 49,
        ModifyThread = 50,
        HasFastTravelAlways = 51,
        KnockdownChance = 52,
        ModifyWeaponStrengthReq = 53,
        ModifyAimingMoveSpeed = 54,
        ModifyLightItems = 55,
        ModifyDamageThresholdDefender = 56,
        ModifyChanceForAmmoItem = 57,
        ModifyDamageThresholdAttacker = 58,
        ModifyThrowingVelocity = 59,
        ChanceForItemOnFire = 60,
        HasUnarmedForwardPowerAttack = 61,
        HasUnarmedBackPowerAttack = 62,
        HasUnarmedCrouchedPowerAttack = 63,
        HasUnarmedCounterAttack = 64,
        HasUnarmedLeftPowerAttack = 65,
        HasUnarmedRightPowerAttack = 66,
        VATSHelperChance = 67,
        ModifyItemDamage = 68,
        HasImprovedDetection = 69,
        HasImprovedSpotting = 70,
        HasImprovedItemDetection = 71,
        AdjustExplosionRadius = 72,
        Reserved = 73,
    }
}
