namespace Mutagen.Bethesda.Fallout76;

public enum KeywordType
{
    None = 0,
    ComponentTechLevel = 1,
    AttachPoint = 2,
    ComponentProperty = 3,
    InstantiationFilter = 4,
    ModAssociation = 5,
    Sound = 6,
    AnimArchetype = 7,
    FunctionCall = 8,
    RecipeFilter = 9,
    AttractionType = 10,
    DialogueSubtype = 11,
    QuestTarget = 12,
    AnimFlavor = 13,
    AnimGender = 14,
    AnimFace = 15,
    AnimFaceRelated = 16,
    SpellEffect = 17,
    MagicItemType = 18,
    CritEffect = 19,
    VoiceType = 20,
    BodyData = 21,
    DialogueAction = 22,
    EncounterZone = 23,
    Message = 24,
    MusicType = 25,
    SoundCategory = 26,
    SharedCrimeFactionList = 27,
    KnowableForm = 28,
    Perk = 29,
    WeaponSubType = 30,
    ConditionForm = 31,
    Unknown32 = 32,
}
