namespace Mutagen.Bethesda.Starfield;

public partial class Keyword
{
    // ToDo
    // Copy Paste Risk
    [Flags]
    public enum MajorFlag
    {
        Restricted = 0x0008_0000
    }

    public enum TypeEnum
    {
        None = 0,
        ComponentTechLevel = 1,
        AttachPoint = 2,
        ComponentProperty = 3,
        InstantiationFilter = 4,
        ModAssociation = 5,
        Sound = 6,
        AnimArchetype = 7,
        FunctionCall = 8,
        RecipeFilter = 9,
        Attraction = 10,
        DialogueSubtype = 11,
        QuestTarget = 12,
        AnimFlavor = 13,
        AnimGender = 14,
        AnimFace = 15,
        QuestGroup = 16,
        AnimInjured = 17,
        DispelEffect = 18,
        CrowdTarget = 19,
        ExclusiveLocationEncounter = 20,
        WeaponHolster = 21,
        HUDMarkerOverride = 22,
        InteractionRootOffset = 23,
        MiscItemQuality = 24,
        ComponentQuantity = 25,
        Quest = 26,
        Faction = 27,
        Traversal = 28,
        InventoryCategory = 29,
        FormLink = 30,
        Manufacturer = 31,
        UIIconPersonalEffect = 32,
        UIIconEnvironmentEffect = 33,
        Primitive = 34,
        Planet = 35,
        PlanetAtmosphere = 36,
        PlanetAtmosphereToxicity = 37,
        PlanetGravity = 38,
        PlanetWaterAbundance = 39,
        PlanetWaterQuality = 40,
        PlanetMagnetosphere = 41,
        PlanetFloraProbability = 42,
        PlanetFaunaProbability = 43,
        PlanetTraits = 44,
        PlanetTemperature = 45,
        PlanetPressure = 46,
        PlanetFloraAbundance = 47,
        PlanetFaunaAbundance = 48,
        BiomeMarker = 49,
        HandScannerInfo = 50,
        ShipModuleClass = 51,
        LayeredMaterialSwapKey = 52,
        UIIconLinkageName = 53,
        Mission = 54,
        SoundEngine = 55,
        SoundEngineMod = 56,
        SoundCockpit = 57,
        SoundGravDrive = 58,
        PerkTraitRestriction = 59,
        SoundCCTSkin = 60,
        SoundCCTSize = 61,
        SoundCCTSpeed = 62,
        PhotoModeCategory = 63,
        ExcludeFromGIOrRaytracing = 64,
        IncludeInGIOrRaytracing = 65,
        HairColor = 66,
        FacialHairColor = 67,
        EyeColor = 68,
        BiomeHoudiniStyle = 69,
        AnimFlavorAnimObject = 70,
        BrowColor = 71,
        HairSubtype = 72,
        FacialHairSubtype = 73,
        BrowSubtype = 74,
        AVMSConditionSequence = 75,
        BiomeCreature = 76,
        ShipModuleUpgrade = 77,
        DisplayName = 78,
        AVMSAppearanceVariationMod = 79,
        UIIconTreatment = 80,
        FormPair = 81,
        ItemDescription = 82,
        WeaponDisplay = 83,
    }
}