/*
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
 * Autogenerated by Loqui.  Do not manually change.
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
*/
#region Usings
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Loqui;
using Loqui.Internal;
using Noggog;
using Mutagen.Bethesda.Skyrim.Internals;
using System.Reactive.Disposables;
using System.Reactive.Linq;
using Mutagen.Bethesda.Skyrim;
using System.Xml;
using System.Xml.Linq;
using System.IO;
using Noggog.Xml;
using Loqui.Xml;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using Mutagen.Bethesda.Xml;
using Mutagen.Bethesda.Binary;
using System.Buffers.Binary;
using Mutagen.Bethesda.Internals;
#endregion

#nullable enable
namespace Mutagen.Bethesda.Skyrim
{
    #region Class
    public partial class Attack :
        IAttack,
        ILoquiObjectSetter<Attack>,
        IEquatable<Attack>,
        IEqualsMask
    {
        #region Ctor
        public Attack()
        {
            CustomCtor();
        }
        partial void CustomCtor();
        #endregion

        #region AttackData
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        private AttackData? _AttackData;
        public AttackData? AttackData
        {
            get => _AttackData;
            set => _AttackData = value;
        }
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        IAttackDataGetter? IAttackGetter.AttackData => this.AttackData;
        #endregion
        #region AttackEvent
        public String? AttackEvent { get; set; }
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        String? IAttackGetter.AttackEvent => this.AttackEvent;
        #endregion

        #region To String

        public void ToString(
            FileGeneration fg,
            string? name = null)
        {
            AttackMixIn.ToString(
                item: this,
                name: name);
        }

        #endregion

        #region Equals and Hash
        public override bool Equals(object? obj)
        {
            if (!(obj is IAttackGetter rhs)) return false;
            return ((AttackCommon)((IAttackGetter)this).CommonInstance()!).Equals(this, rhs);
        }

        public bool Equals(Attack? obj)
        {
            return ((AttackCommon)((IAttackGetter)this).CommonInstance()!).Equals(this, obj);
        }

        public override int GetHashCode() => ((AttackCommon)((IAttackGetter)this).CommonInstance()!).GetHashCode(this);

        #endregion

        #region Xml Translation
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        protected object XmlWriteTranslator => AttackXmlWriteTranslation.Instance;
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        object IXmlItem.XmlWriteTranslator => this.XmlWriteTranslator;
        void IXmlItem.WriteToXml(
            XElement node,
            ErrorMaskBuilder? errorMask,
            TranslationCrystal? translationMask,
            string? name = null)
        {
            ((AttackXmlWriteTranslation)this.XmlWriteTranslator).Write(
                item: this,
                name: name,
                node: node,
                errorMask: errorMask,
                translationMask: translationMask);
        }
        #region Xml Create
        [DebuggerStepThrough]
        public static Attack CreateFromXml(
            XElement node,
            Attack.TranslationMask? translationMask = null)
        {
            return CreateFromXml(
                node: node,
                errorMask: null,
                translationMask: translationMask?.GetCrystal());
        }

        [DebuggerStepThrough]
        public static Attack CreateFromXml(
            XElement node,
            out Attack.ErrorMask errorMask,
            Attack.TranslationMask? translationMask = null)
        {
            ErrorMaskBuilder errorMaskBuilder = new ErrorMaskBuilder();
            var ret = CreateFromXml(
                node: node,
                errorMask: errorMaskBuilder,
                translationMask: translationMask?.GetCrystal());
            errorMask = Attack.ErrorMask.Factory(errorMaskBuilder);
            return ret;
        }

        public static Attack CreateFromXml(
            XElement node,
            ErrorMaskBuilder? errorMask,
            TranslationCrystal? translationMask)
        {
            var ret = new Attack();
            ((AttackSetterCommon)((IAttackGetter)ret).CommonSetterInstance()!).CopyInFromXml(
                item: ret,
                node: node,
                errorMask: errorMask,
                translationMask: translationMask);
            return ret;
        }

        public static Attack CreateFromXml(
            string path,
            Attack.TranslationMask? translationMask = null)
        {
            var node = XDocument.Load(path).Root;
            return CreateFromXml(
                node: node,
                translationMask: translationMask);
        }

        public static Attack CreateFromXml(
            string path,
            out Attack.ErrorMask errorMask,
            Attack.TranslationMask? translationMask = null)
        {
            var node = XDocument.Load(path).Root;
            return CreateFromXml(
                node: node,
                errorMask: out errorMask,
                translationMask: translationMask);
        }

        public static Attack CreateFromXml(
            string path,
            ErrorMaskBuilder? errorMask,
            Attack.TranslationMask? translationMask = null)
        {
            var node = XDocument.Load(path).Root;
            return CreateFromXml(
                node: node,
                errorMask: errorMask,
                translationMask: translationMask?.GetCrystal());
        }

        public static Attack CreateFromXml(
            Stream stream,
            Attack.TranslationMask? translationMask = null)
        {
            var node = XDocument.Load(stream).Root;
            return CreateFromXml(
                node: node,
                translationMask: translationMask);
        }

        public static Attack CreateFromXml(
            Stream stream,
            out Attack.ErrorMask errorMask,
            Attack.TranslationMask? translationMask = null)
        {
            var node = XDocument.Load(stream).Root;
            return CreateFromXml(
                node: node,
                errorMask: out errorMask,
                translationMask: translationMask);
        }

        public static Attack CreateFromXml(
            Stream stream,
            ErrorMaskBuilder? errorMask,
            Attack.TranslationMask? translationMask = null)
        {
            var node = XDocument.Load(stream).Root;
            return CreateFromXml(
                node: node,
                errorMask: errorMask,
                translationMask: translationMask?.GetCrystal());
        }

        #endregion

        #endregion

        #region Mask
        public class Mask<TItem> :
            IMask<TItem>,
            IEquatable<Mask<TItem>>
        {
            #region Ctors
            public Mask(TItem initialValue)
            {
                this.AttackData = new MaskItem<TItem, AttackData.Mask<TItem>?>(initialValue, new AttackData.Mask<TItem>(initialValue));
                this.AttackEvent = initialValue;
            }

            public Mask(
                TItem AttackData,
                TItem AttackEvent)
            {
                this.AttackData = new MaskItem<TItem, AttackData.Mask<TItem>?>(AttackData, new AttackData.Mask<TItem>(AttackData));
                this.AttackEvent = AttackEvent;
            }

            #pragma warning disable CS8618
            protected Mask()
            {
            }
            #pragma warning restore CS8618

            #endregion

            #region Members
            public MaskItem<TItem, AttackData.Mask<TItem>?>? AttackData { get; set; }
            public TItem AttackEvent;
            #endregion

            #region Equals
            public override bool Equals(object? obj)
            {
                if (!(obj is Mask<TItem> rhs)) return false;
                return Equals(rhs);
            }

            public bool Equals(Mask<TItem>? rhs)
            {
                if (rhs == null) return false;
                if (!object.Equals(this.AttackData, rhs.AttackData)) return false;
                if (!object.Equals(this.AttackEvent, rhs.AttackEvent)) return false;
                return true;
            }
            public override int GetHashCode()
            {
                var hash = new HashCode();
                hash.Add(this.AttackData);
                hash.Add(this.AttackEvent);
                return hash.ToHashCode();
            }

            #endregion

            #region All
            public bool All(Func<TItem, bool> eval)
            {
                if (AttackData != null)
                {
                    if (!eval(this.AttackData.Overall)) return false;
                    if (this.AttackData.Specific != null && !this.AttackData.Specific.All(eval)) return false;
                }
                if (!eval(this.AttackEvent)) return false;
                return true;
            }
            #endregion

            #region Any
            public bool Any(Func<TItem, bool> eval)
            {
                if (AttackData != null)
                {
                    if (eval(this.AttackData.Overall)) return true;
                    if (this.AttackData.Specific != null && this.AttackData.Specific.Any(eval)) return true;
                }
                if (eval(this.AttackEvent)) return true;
                return false;
            }
            #endregion

            #region Translate
            public Mask<R> Translate<R>(Func<TItem, R> eval)
            {
                var ret = new Attack.Mask<R>();
                this.Translate_InternalFill(ret, eval);
                return ret;
            }

            protected void Translate_InternalFill<R>(Mask<R> obj, Func<TItem, R> eval)
            {
                obj.AttackData = this.AttackData == null ? null : new MaskItem<R, AttackData.Mask<R>?>(eval(this.AttackData.Overall), this.AttackData.Specific?.Translate(eval));
                obj.AttackEvent = eval(this.AttackEvent);
            }
            #endregion

            #region To String
            public override string ToString()
            {
                return ToString(printMask: null);
            }

            public string ToString(Attack.Mask<bool>? printMask = null)
            {
                var fg = new FileGeneration();
                ToString(fg, printMask);
                return fg.ToString();
            }

            public void ToString(FileGeneration fg, Attack.Mask<bool>? printMask = null)
            {
                fg.AppendLine($"{nameof(Attack.Mask<TItem>)} =>");
                fg.AppendLine("[");
                using (new DepthWrapper(fg))
                {
                    if (printMask?.AttackData?.Overall ?? true)
                    {
                        AttackData?.ToString(fg);
                    }
                    if (printMask?.AttackEvent ?? true)
                    {
                        fg.AppendItem(AttackEvent, "AttackEvent");
                    }
                }
                fg.AppendLine("]");
            }
            #endregion

        }

        public class ErrorMask :
            IErrorMask,
            IErrorMask<ErrorMask>
        {
            #region Members
            public Exception? Overall { get; set; }
            private List<string>? _warnings;
            public List<string> Warnings
            {
                get
                {
                    if (_warnings == null)
                    {
                        _warnings = new List<string>();
                    }
                    return _warnings;
                }
            }
            public MaskItem<Exception?, AttackData.ErrorMask?>? AttackData;
            public Exception? AttackEvent;
            #endregion

            #region IErrorMask
            public object? GetNthMask(int index)
            {
                Attack_FieldIndex enu = (Attack_FieldIndex)index;
                switch (enu)
                {
                    case Attack_FieldIndex.AttackData:
                        return AttackData;
                    case Attack_FieldIndex.AttackEvent:
                        return AttackEvent;
                    default:
                        throw new ArgumentException($"Index is out of range: {index}");
                }
            }

            public void SetNthException(int index, Exception ex)
            {
                Attack_FieldIndex enu = (Attack_FieldIndex)index;
                switch (enu)
                {
                    case Attack_FieldIndex.AttackData:
                        this.AttackData = new MaskItem<Exception?, AttackData.ErrorMask?>(ex, null);
                        break;
                    case Attack_FieldIndex.AttackEvent:
                        this.AttackEvent = ex;
                        break;
                    default:
                        throw new ArgumentException($"Index is out of range: {index}");
                }
            }

            public void SetNthMask(int index, object obj)
            {
                Attack_FieldIndex enu = (Attack_FieldIndex)index;
                switch (enu)
                {
                    case Attack_FieldIndex.AttackData:
                        this.AttackData = (MaskItem<Exception?, AttackData.ErrorMask?>?)obj;
                        break;
                    case Attack_FieldIndex.AttackEvent:
                        this.AttackEvent = (Exception?)obj;
                        break;
                    default:
                        throw new ArgumentException($"Index is out of range: {index}");
                }
            }

            public bool IsInError()
            {
                if (Overall != null) return true;
                if (AttackData != null) return true;
                if (AttackEvent != null) return true;
                return false;
            }
            #endregion

            #region To String
            public override string ToString()
            {
                var fg = new FileGeneration();
                ToString(fg, null);
                return fg.ToString();
            }

            public void ToString(FileGeneration fg, string? name = null)
            {
                fg.AppendLine($"{(name ?? "ErrorMask")} =>");
                fg.AppendLine("[");
                using (new DepthWrapper(fg))
                {
                    if (this.Overall != null)
                    {
                        fg.AppendLine("Overall =>");
                        fg.AppendLine("[");
                        using (new DepthWrapper(fg))
                        {
                            fg.AppendLine($"{this.Overall}");
                        }
                        fg.AppendLine("]");
                    }
                    ToString_FillInternal(fg);
                }
                fg.AppendLine("]");
            }
            protected void ToString_FillInternal(FileGeneration fg)
            {
                AttackData?.ToString(fg);
                fg.AppendItem(AttackEvent, "AttackEvent");
            }
            #endregion

            #region Combine
            public ErrorMask Combine(ErrorMask? rhs)
            {
                if (rhs == null) return this;
                var ret = new ErrorMask();
                ret.AttackData = this.AttackData.Combine(rhs.AttackData, (l, r) => l.Combine(r));
                ret.AttackEvent = this.AttackEvent.Combine(rhs.AttackEvent);
                return ret;
            }
            public static ErrorMask? Combine(ErrorMask? lhs, ErrorMask? rhs)
            {
                if (lhs != null && rhs != null) return lhs.Combine(rhs);
                return lhs ?? rhs;
            }
            #endregion

            #region Factory
            public static ErrorMask Factory(ErrorMaskBuilder errorMask)
            {
                return new ErrorMask();
            }
            #endregion

        }
        public class TranslationMask : ITranslationMask
        {
            #region Members
            private TranslationCrystal? _crystal;
            public MaskItem<bool, AttackData.TranslationMask?> AttackData;
            public bool AttackEvent;
            #endregion

            #region Ctors
            public TranslationMask(bool defaultOn)
            {
                this.AttackData = new MaskItem<bool, AttackData.TranslationMask?>(defaultOn, null);
                this.AttackEvent = defaultOn;
            }

            #endregion

            public TranslationCrystal GetCrystal()
            {
                if (_crystal != null) return _crystal;
                var ret = new List<(bool On, TranslationCrystal? SubCrystal)>();
                GetCrystal(ret);
                _crystal = new TranslationCrystal(ret.ToArray());
                return _crystal;
            }

            protected void GetCrystal(List<(bool On, TranslationCrystal? SubCrystal)> ret)
            {
                ret.Add((AttackData?.Overall ?? true, AttackData?.Specific?.GetCrystal()));
                ret.Add((AttackEvent, null));
            }
        }
        #endregion

        #region Mutagen
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        protected IEnumerable<FormKey> LinkFormKeys => AttackCommon.Instance.GetLinkFormKeys(this);
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        IEnumerable<FormKey> ILinkedFormKeyContainer.LinkFormKeys => AttackCommon.Instance.GetLinkFormKeys(this);
        protected void RemapLinks(IReadOnlyDictionary<FormKey, FormKey> mapping) => AttackCommon.Instance.RemapLinks(this, mapping);
        void ILinkedFormKeyContainer.RemapLinks(IReadOnlyDictionary<FormKey, FormKey> mapping) => AttackCommon.Instance.RemapLinks(this, mapping);
        #endregion

        #region Binary Translation
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        protected object BinaryWriteTranslator => AttackBinaryWriteTranslation.Instance;
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        object IBinaryItem.BinaryWriteTranslator => this.BinaryWriteTranslator;
        void IBinaryItem.WriteToBinary(
            MutagenWriter writer,
            RecordTypeConverter? recordTypeConverter = null)
        {
            ((AttackBinaryWriteTranslation)this.BinaryWriteTranslator).Write(
                item: this,
                writer: writer,
                recordTypeConverter: recordTypeConverter);
        }
        #region Binary Create
        [DebuggerStepThrough]
        public static Attack CreateFromBinary(MutagenFrame frame)
        {
            return CreateFromBinary(
                frame: frame,
                recordTypeConverter: null);
        }

        public static Attack CreateFromBinary(
            MutagenFrame frame,
            RecordTypeConverter? recordTypeConverter = null)
        {
            var ret = new Attack();
            ((AttackSetterCommon)((IAttackGetter)ret).CommonSetterInstance()!).CopyInFromBinary(
                item: ret,
                frame: frame,
                recordTypeConverter: recordTypeConverter);
            return ret;
        }

        #endregion

        public static bool TryCreateFromBinary(
            MutagenFrame frame,
            out Attack item,
            RecordTypeConverter? recordTypeConverter = null)
        {
            var startPos = frame.Position;
            item = CreateFromBinary(frame, recordTypeConverter);
            return startPos != frame.Position;
        }
        #endregion

        void IPrintable.ToString(FileGeneration fg, string? name) => this.ToString(fg, name);
        IMask<bool> ILoquiObjectGetter.GetHasBeenSetIMask() => this.GetHasBeenSetMask();
        IMask<bool> IEqualsMask.GetEqualsIMask(object rhs, EqualsMaskHelper.Include include) => this.GetEqualsMask((IAttackGetter)rhs, include);

        void IClearable.Clear()
        {
            ((AttackSetterCommon)((IAttackGetter)this).CommonSetterInstance()!).Clear(this);
        }

        internal static Attack GetNew()
        {
            return new Attack();
        }

    }
    #endregion

    #region Interface
    public partial interface IAttack :
        IAttackGetter,
        ILoquiObjectSetter<IAttack>
    {
        new AttackData? AttackData { get; set; }
        new String? AttackEvent { get; set; }
    }

    public partial interface IAttackGetter :
        ILoquiObject,
        ILoquiObject<IAttackGetter>,
        IXmlItem,
        ILinkedFormKeyContainer,
        IBinaryItem
    {
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        object CommonInstance();
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        object? CommonSetterInstance();
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        object CommonSetterTranslationInstance();
        static ILoquiRegistration Registration => Attack_Registration.Instance;
        IAttackDataGetter? AttackData { get; }
        String? AttackEvent { get; }

    }

    #endregion

    #region Common MixIn
    public static partial class AttackMixIn
    {
        public static void Clear(this IAttack item)
        {
            ((AttackSetterCommon)((IAttackGetter)item).CommonSetterInstance()!).Clear(item: item);
        }

        public static Attack.Mask<bool> GetEqualsMask(
            this IAttackGetter item,
            IAttackGetter rhs,
            EqualsMaskHelper.Include include = EqualsMaskHelper.Include.All)
        {
            return ((AttackCommon)((IAttackGetter)item).CommonInstance()!).GetEqualsMask(
                item: item,
                rhs: rhs,
                include: include);
        }

        public static string ToString(
            this IAttackGetter item,
            string? name = null,
            Attack.Mask<bool>? printMask = null)
        {
            return ((AttackCommon)((IAttackGetter)item).CommonInstance()!).ToString(
                item: item,
                name: name,
                printMask: printMask);
        }

        public static void ToString(
            this IAttackGetter item,
            FileGeneration fg,
            string? name = null,
            Attack.Mask<bool>? printMask = null)
        {
            ((AttackCommon)((IAttackGetter)item).CommonInstance()!).ToString(
                item: item,
                fg: fg,
                name: name,
                printMask: printMask);
        }

        public static bool HasBeenSet(
            this IAttackGetter item,
            Attack.Mask<bool?> checkMask)
        {
            return ((AttackCommon)((IAttackGetter)item).CommonInstance()!).HasBeenSet(
                item: item,
                checkMask: checkMask);
        }

        public static Attack.Mask<bool> GetHasBeenSetMask(this IAttackGetter item)
        {
            var ret = new Attack.Mask<bool>(false);
            ((AttackCommon)((IAttackGetter)item).CommonInstance()!).FillHasBeenSetMask(
                item: item,
                mask: ret);
            return ret;
        }

        public static bool Equals(
            this IAttackGetter item,
            IAttackGetter rhs)
        {
            return ((AttackCommon)((IAttackGetter)item).CommonInstance()!).Equals(
                lhs: item,
                rhs: rhs);
        }

        public static void DeepCopyIn(
            this IAttack lhs,
            IAttackGetter rhs)
        {
            ((AttackSetterTranslationCommon)((IAttackGetter)lhs).CommonSetterTranslationInstance()!).DeepCopyIn(
                item: lhs,
                rhs: rhs,
                errorMask: default,
                copyMask: default);
        }

        public static void DeepCopyIn(
            this IAttack lhs,
            IAttackGetter rhs,
            Attack.TranslationMask? copyMask = null)
        {
            ((AttackSetterTranslationCommon)((IAttackGetter)lhs).CommonSetterTranslationInstance()!).DeepCopyIn(
                item: lhs,
                rhs: rhs,
                errorMask: default,
                copyMask: copyMask?.GetCrystal());
        }

        public static void DeepCopyIn(
            this IAttack lhs,
            IAttackGetter rhs,
            out Attack.ErrorMask errorMask,
            Attack.TranslationMask? copyMask = null)
        {
            var errorMaskBuilder = new ErrorMaskBuilder();
            ((AttackSetterTranslationCommon)((IAttackGetter)lhs).CommonSetterTranslationInstance()!).DeepCopyIn(
                item: lhs,
                rhs: rhs,
                errorMask: errorMaskBuilder,
                copyMask: copyMask?.GetCrystal());
            errorMask = Attack.ErrorMask.Factory(errorMaskBuilder);
        }

        public static void DeepCopyIn(
            this IAttack lhs,
            IAttackGetter rhs,
            ErrorMaskBuilder? errorMask,
            TranslationCrystal? copyMask)
        {
            ((AttackSetterTranslationCommon)((IAttackGetter)lhs).CommonSetterTranslationInstance()!).DeepCopyIn(
                item: lhs,
                rhs: rhs,
                errorMask: errorMask,
                copyMask: copyMask);
        }

        public static Attack DeepCopy(
            this IAttackGetter item,
            Attack.TranslationMask? copyMask = null)
        {
            return ((AttackSetterTranslationCommon)((IAttackGetter)item).CommonSetterTranslationInstance()!).DeepCopy(
                item: item,
                copyMask: copyMask);
        }

        public static Attack DeepCopy(
            this IAttackGetter item,
            out Attack.ErrorMask errorMask,
            Attack.TranslationMask? copyMask = null)
        {
            return ((AttackSetterTranslationCommon)((IAttackGetter)item).CommonSetterTranslationInstance()!).DeepCopy(
                item: item,
                copyMask: copyMask,
                errorMask: out errorMask);
        }

        public static Attack DeepCopy(
            this IAttackGetter item,
            ErrorMaskBuilder? errorMask,
            TranslationCrystal? copyMask = null)
        {
            return ((AttackSetterTranslationCommon)((IAttackGetter)item).CommonSetterTranslationInstance()!).DeepCopy(
                item: item,
                copyMask: copyMask,
                errorMask: errorMask);
        }

        #region Xml Translation
        [DebuggerStepThrough]
        public static void CopyInFromXml(
            this IAttack item,
            XElement node,
            Attack.TranslationMask? translationMask = null)
        {
            CopyInFromXml(
                item: item,
                node: node,
                errorMask: null,
                translationMask: translationMask?.GetCrystal());
        }

        [DebuggerStepThrough]
        public static void CopyInFromXml(
            this IAttack item,
            XElement node,
            out Attack.ErrorMask errorMask,
            Attack.TranslationMask? translationMask = null)
        {
            ErrorMaskBuilder errorMaskBuilder = new ErrorMaskBuilder();
            CopyInFromXml(
                item: item,
                node: node,
                errorMask: errorMaskBuilder,
                translationMask: translationMask?.GetCrystal());
            errorMask = Attack.ErrorMask.Factory(errorMaskBuilder);
        }

        public static void CopyInFromXml(
            this IAttack item,
            XElement node,
            ErrorMaskBuilder? errorMask,
            TranslationCrystal? translationMask)
        {
            ((AttackSetterCommon)((IAttackGetter)item).CommonSetterInstance()!).CopyInFromXml(
                item: item,
                node: node,
                errorMask: errorMask,
                translationMask: translationMask);
        }

        public static void CopyInFromXml(
            this IAttack item,
            string path,
            Attack.TranslationMask? translationMask = null)
        {
            var node = XDocument.Load(path).Root;
            CopyInFromXml(
                item: item,
                node: node,
                translationMask: translationMask);
        }

        public static void CopyInFromXml(
            this IAttack item,
            string path,
            out Attack.ErrorMask errorMask,
            Attack.TranslationMask? translationMask = null)
        {
            var node = XDocument.Load(path).Root;
            CopyInFromXml(
                item: item,
                node: node,
                errorMask: out errorMask,
                translationMask: translationMask);
        }

        public static void CopyInFromXml(
            this IAttack item,
            string path,
            ErrorMaskBuilder? errorMask,
            Attack.TranslationMask? translationMask = null)
        {
            var node = XDocument.Load(path).Root;
            CopyInFromXml(
                item: item,
                node: node,
                errorMask: errorMask,
                translationMask: translationMask?.GetCrystal());
        }

        public static void CopyInFromXml(
            this IAttack item,
            Stream stream,
            Attack.TranslationMask? translationMask = null)
        {
            var node = XDocument.Load(stream).Root;
            CopyInFromXml(
                item: item,
                node: node,
                translationMask: translationMask);
        }

        public static void CopyInFromXml(
            this IAttack item,
            Stream stream,
            out Attack.ErrorMask errorMask,
            Attack.TranslationMask? translationMask = null)
        {
            var node = XDocument.Load(stream).Root;
            CopyInFromXml(
                item: item,
                node: node,
                errorMask: out errorMask,
                translationMask: translationMask);
        }

        public static void CopyInFromXml(
            this IAttack item,
            Stream stream,
            ErrorMaskBuilder? errorMask,
            Attack.TranslationMask? translationMask = null)
        {
            var node = XDocument.Load(stream).Root;
            CopyInFromXml(
                item: item,
                node: node,
                errorMask: errorMask,
                translationMask: translationMask?.GetCrystal());
        }

        #endregion

        #region Binary Translation
        [DebuggerStepThrough]
        public static void CopyInFromBinary(
            this IAttack item,
            MutagenFrame frame)
        {
            CopyInFromBinary(
                item: item,
                frame: frame,
                recordTypeConverter: null);
        }

        public static void CopyInFromBinary(
            this IAttack item,
            MutagenFrame frame,
            RecordTypeConverter? recordTypeConverter = null)
        {
            ((AttackSetterCommon)((IAttackGetter)item).CommonSetterInstance()!).CopyInFromBinary(
                item: item,
                frame: frame,
                recordTypeConverter: recordTypeConverter);
        }

        #endregion

    }
    #endregion

}

namespace Mutagen.Bethesda.Skyrim.Internals
{
    #region Field Index
    public enum Attack_FieldIndex
    {
        AttackData = 0,
        AttackEvent = 1,
    }
    #endregion

    #region Registration
    public partial class Attack_Registration : ILoquiRegistration
    {
        public static readonly Attack_Registration Instance = new Attack_Registration();

        public static ProtocolKey ProtocolKey => ProtocolDefinition_Skyrim.ProtocolKey;

        public static readonly ObjectKey ObjectKey = new ObjectKey(
            protocolKey: ProtocolDefinition_Skyrim.ProtocolKey,
            msgID: 57,
            version: 0);

        public const string GUID = "c6031cd8-bc21-4fbe-b9e5-395a8ca68c9f";

        public const ushort AdditionalFieldCount = 2;

        public const ushort FieldCount = 2;

        public static readonly Type MaskType = typeof(Attack.Mask<>);

        public static readonly Type ErrorMaskType = typeof(Attack.ErrorMask);

        public static readonly Type ClassType = typeof(Attack);

        public static readonly Type GetterType = typeof(IAttackGetter);

        public static readonly Type? InternalGetterType = null;

        public static readonly Type SetterType = typeof(IAttack);

        public static readonly Type? InternalSetterType = null;

        public const string FullName = "Mutagen.Bethesda.Skyrim.Attack";

        public const string Name = "Attack";

        public const string Namespace = "Mutagen.Bethesda.Skyrim";

        public const byte GenericCount = 0;

        public static readonly Type? GenericRegistrationType = null;

        public static ushort? GetNameIndex(StringCaseAgnostic str)
        {
            switch (str.Upper)
            {
                case "ATTACKDATA":
                    return (ushort)Attack_FieldIndex.AttackData;
                case "ATTACKEVENT":
                    return (ushort)Attack_FieldIndex.AttackEvent;
                default:
                    return null;
            }
        }

        public static bool GetNthIsEnumerable(ushort index)
        {
            Attack_FieldIndex enu = (Attack_FieldIndex)index;
            switch (enu)
            {
                case Attack_FieldIndex.AttackData:
                case Attack_FieldIndex.AttackEvent:
                    return false;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static bool GetNthIsLoqui(ushort index)
        {
            Attack_FieldIndex enu = (Attack_FieldIndex)index;
            switch (enu)
            {
                case Attack_FieldIndex.AttackData:
                    return true;
                case Attack_FieldIndex.AttackEvent:
                    return false;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static bool GetNthIsSingleton(ushort index)
        {
            Attack_FieldIndex enu = (Attack_FieldIndex)index;
            switch (enu)
            {
                case Attack_FieldIndex.AttackData:
                case Attack_FieldIndex.AttackEvent:
                    return false;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static string GetNthName(ushort index)
        {
            Attack_FieldIndex enu = (Attack_FieldIndex)index;
            switch (enu)
            {
                case Attack_FieldIndex.AttackData:
                    return "AttackData";
                case Attack_FieldIndex.AttackEvent:
                    return "AttackEvent";
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static bool IsNthDerivative(ushort index)
        {
            Attack_FieldIndex enu = (Attack_FieldIndex)index;
            switch (enu)
            {
                case Attack_FieldIndex.AttackData:
                case Attack_FieldIndex.AttackEvent:
                    return false;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static bool IsProtected(ushort index)
        {
            Attack_FieldIndex enu = (Attack_FieldIndex)index;
            switch (enu)
            {
                case Attack_FieldIndex.AttackData:
                case Attack_FieldIndex.AttackEvent:
                    return false;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static Type GetNthType(ushort index)
        {
            Attack_FieldIndex enu = (Attack_FieldIndex)index;
            switch (enu)
            {
                case Attack_FieldIndex.AttackData:
                    return typeof(AttackData);
                case Attack_FieldIndex.AttackEvent:
                    return typeof(String);
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static readonly Type XmlWriteTranslation = typeof(AttackXmlWriteTranslation);
        public static ICollectionGetter<RecordType> TriggeringRecordTypes => _TriggeringRecordTypes.Value;
        private static readonly Lazy<ICollectionGetter<RecordType>> _TriggeringRecordTypes = new Lazy<ICollectionGetter<RecordType>>(() =>
        {
            return new CollectionGetterWrapper<RecordType>(
                new HashSet<RecordType>(
                    new RecordType[]
                    {
                        RecordTypes.ATKD,
                        RecordTypes.ATKE
                    })
            );
        });
        public static readonly Type BinaryWriteTranslation = typeof(AttackBinaryWriteTranslation);
        #region Interface
        ProtocolKey ILoquiRegistration.ProtocolKey => ProtocolKey;
        ObjectKey ILoquiRegistration.ObjectKey => ObjectKey;
        string ILoquiRegistration.GUID => GUID;
        ushort ILoquiRegistration.FieldCount => FieldCount;
        ushort ILoquiRegistration.AdditionalFieldCount => AdditionalFieldCount;
        Type ILoquiRegistration.MaskType => MaskType;
        Type ILoquiRegistration.ErrorMaskType => ErrorMaskType;
        Type ILoquiRegistration.ClassType => ClassType;
        Type ILoquiRegistration.SetterType => SetterType;
        Type? ILoquiRegistration.InternalSetterType => InternalSetterType;
        Type ILoquiRegistration.GetterType => GetterType;
        Type? ILoquiRegistration.InternalGetterType => InternalGetterType;
        string ILoquiRegistration.FullName => FullName;
        string ILoquiRegistration.Name => Name;
        string ILoquiRegistration.Namespace => Namespace;
        byte ILoquiRegistration.GenericCount => GenericCount;
        Type? ILoquiRegistration.GenericRegistrationType => GenericRegistrationType;
        ushort? ILoquiRegistration.GetNameIndex(StringCaseAgnostic name) => GetNameIndex(name);
        bool ILoquiRegistration.GetNthIsEnumerable(ushort index) => GetNthIsEnumerable(index);
        bool ILoquiRegistration.GetNthIsLoqui(ushort index) => GetNthIsLoqui(index);
        bool ILoquiRegistration.GetNthIsSingleton(ushort index) => GetNthIsSingleton(index);
        string ILoquiRegistration.GetNthName(ushort index) => GetNthName(index);
        bool ILoquiRegistration.IsNthDerivative(ushort index) => IsNthDerivative(index);
        bool ILoquiRegistration.IsProtected(ushort index) => IsProtected(index);
        Type ILoquiRegistration.GetNthType(ushort index) => GetNthType(index);
        #endregion

    }
    #endregion

    #region Common
    public partial class AttackSetterCommon
    {
        public static readonly AttackSetterCommon Instance = new AttackSetterCommon();

        partial void ClearPartial();
        
        public void Clear(IAttack item)
        {
            ClearPartial();
            item.AttackData = null;
            item.AttackEvent = default;
        }
        
        #region Xml Translation
        public virtual void CopyInFromXml(
            IAttack item,
            XElement node,
            ErrorMaskBuilder? errorMask,
            TranslationCrystal? translationMask)
        {
            try
            {
                foreach (var elem in node.Elements())
                {
                    AttackXmlCreateTranslation.FillPublicElementXml(
                        item: item,
                        node: elem,
                        name: elem.Name.LocalName,
                        errorMask: errorMask,
                        translationMask: translationMask);
                }
            }
            catch (Exception ex)
            when (errorMask != null)
            {
                errorMask.ReportException(ex);
            }
        }
        
        #endregion
        
        #region Binary Translation
        public virtual void CopyInFromBinary(
            IAttack item,
            MutagenFrame frame,
            RecordTypeConverter? recordTypeConverter = null)
        {
            UtilityTranslation.SubrecordParse(
                record: item,
                frame: frame,
                recordTypeConverter: recordTypeConverter,
                fillStructs: AttackBinaryCreateTranslation.FillBinaryStructs,
                fillTyped: AttackBinaryCreateTranslation.FillBinaryRecordTypes);
        }
        
        #endregion
        
    }
    public partial class AttackCommon
    {
        public static readonly AttackCommon Instance = new AttackCommon();

        public Attack.Mask<bool> GetEqualsMask(
            IAttackGetter item,
            IAttackGetter rhs,
            EqualsMaskHelper.Include include = EqualsMaskHelper.Include.All)
        {
            var ret = new Attack.Mask<bool>(false);
            ((AttackCommon)((IAttackGetter)item).CommonInstance()!).FillEqualsMask(
                item: item,
                rhs: rhs,
                ret: ret,
                include: include);
            return ret;
        }
        
        public void FillEqualsMask(
            IAttackGetter item,
            IAttackGetter rhs,
            Attack.Mask<bool> ret,
            EqualsMaskHelper.Include include = EqualsMaskHelper.Include.All)
        {
            if (rhs == null) return;
            ret.AttackData = EqualsMaskHelper.EqualsHelper(
                item.AttackData,
                rhs.AttackData,
                (loqLhs, loqRhs, incl) => loqLhs.GetEqualsMask(loqRhs, incl),
                include);
            ret.AttackEvent = string.Equals(item.AttackEvent, rhs.AttackEvent);
        }
        
        public string ToString(
            IAttackGetter item,
            string? name = null,
            Attack.Mask<bool>? printMask = null)
        {
            var fg = new FileGeneration();
            ToString(
                item: item,
                fg: fg,
                name: name,
                printMask: printMask);
            return fg.ToString();
        }
        
        public void ToString(
            IAttackGetter item,
            FileGeneration fg,
            string? name = null,
            Attack.Mask<bool>? printMask = null)
        {
            if (name == null)
            {
                fg.AppendLine($"Attack =>");
            }
            else
            {
                fg.AppendLine($"{name} (Attack) =>");
            }
            fg.AppendLine("[");
            using (new DepthWrapper(fg))
            {
                ToStringFields(
                    item: item,
                    fg: fg,
                    printMask: printMask);
            }
            fg.AppendLine("]");
        }
        
        protected static void ToStringFields(
            IAttackGetter item,
            FileGeneration fg,
            Attack.Mask<bool>? printMask = null)
        {
            if ((printMask?.AttackData?.Overall ?? true)
                && item.AttackData.TryGet(out var AttackDataItem))
            {
                AttackDataItem?.ToString(fg, "AttackData");
            }
            if ((printMask?.AttackEvent ?? true)
                && item.AttackEvent.TryGet(out var AttackEventItem))
            {
                fg.AppendItem(AttackEventItem, "AttackEvent");
            }
        }
        
        public bool HasBeenSet(
            IAttackGetter item,
            Attack.Mask<bool?> checkMask)
        {
            if (checkMask.AttackData?.Overall.HasValue ?? false && checkMask.AttackData.Overall.Value != (item.AttackData != null)) return false;
            if (checkMask.AttackData?.Specific != null && (item.AttackData == null || !item.AttackData.HasBeenSet(checkMask.AttackData.Specific))) return false;
            if (checkMask.AttackEvent.HasValue && checkMask.AttackEvent.Value != (item.AttackEvent != null)) return false;
            return true;
        }
        
        public void FillHasBeenSetMask(
            IAttackGetter item,
            Attack.Mask<bool> mask)
        {
            var itemAttackData = item.AttackData;
            mask.AttackData = new MaskItem<bool, AttackData.Mask<bool>?>(itemAttackData != null, itemAttackData?.GetHasBeenSetMask());
            mask.AttackEvent = (item.AttackEvent != null);
        }
        
        #region Equals and Hash
        public virtual bool Equals(
            IAttackGetter? lhs,
            IAttackGetter? rhs)
        {
            if (lhs == null && rhs == null) return false;
            if (lhs == null || rhs == null) return false;
            if (!object.Equals(lhs.AttackData, rhs.AttackData)) return false;
            if (!string.Equals(lhs.AttackEvent, rhs.AttackEvent)) return false;
            return true;
        }
        
        public virtual int GetHashCode(IAttackGetter item)
        {
            var hash = new HashCode();
            if (item.AttackData.TryGet(out var AttackDataitem))
            {
                hash.Add(AttackDataitem);
            }
            if (item.AttackEvent.TryGet(out var AttackEventitem))
            {
                hash.Add(AttackEventitem);
            }
            return hash.ToHashCode();
        }
        
        #endregion
        
        
        public object GetNew()
        {
            return Attack.GetNew();
        }
        
        #region Mutagen
        public IEnumerable<FormKey> GetLinkFormKeys(IAttackGetter obj)
        {
            if (obj.AttackData.TryGet(out var AttackDataItems))
            {
                foreach (var item in AttackDataItems.LinkFormKeys)
                {
                    yield return item;
                }
            }
            yield break;
        }
        
        public void RemapLinks(IAttackGetter obj, IReadOnlyDictionary<FormKey, FormKey> mapping) => throw new NotImplementedException();
        #endregion
        
    }
    public partial class AttackSetterTranslationCommon
    {
        public static readonly AttackSetterTranslationCommon Instance = new AttackSetterTranslationCommon();

        #region Deep Copy Fields From
        public void DeepCopyIn(
            IAttack item,
            IAttackGetter rhs,
            ErrorMaskBuilder? errorMask,
            TranslationCrystal? copyMask)
        {
            if ((copyMask?.GetShouldTranslate((int)Attack_FieldIndex.AttackData) ?? true))
            {
                errorMask?.PushIndex((int)Attack_FieldIndex.AttackData);
                try
                {
                    if(rhs.AttackData.TryGet(out var rhsAttackData))
                    {
                        item.AttackData = rhsAttackData.DeepCopy(
                            errorMask: errorMask,
                            copyMask?.GetSubCrystal((int)Attack_FieldIndex.AttackData));
                    }
                    else
                    {
                        item.AttackData = default;
                    }
                }
                catch (Exception ex)
                when (errorMask != null)
                {
                    errorMask.ReportException(ex);
                }
                finally
                {
                    errorMask?.PopIndex();
                }
            }
            if ((copyMask?.GetShouldTranslate((int)Attack_FieldIndex.AttackEvent) ?? true))
            {
                item.AttackEvent = rhs.AttackEvent;
            }
        }
        
        #endregion
        
        public Attack DeepCopy(
            IAttackGetter item,
            Attack.TranslationMask? copyMask = null)
        {
            Attack ret = (Attack)((AttackCommon)((IAttackGetter)item).CommonInstance()!).GetNew();
            ret.DeepCopyIn(
                item,
                copyMask: copyMask);
            return ret;
        }
        
        public Attack DeepCopy(
            IAttackGetter item,
            out Attack.ErrorMask errorMask,
            Attack.TranslationMask? copyMask = null)
        {
            Attack ret = (Attack)((AttackCommon)((IAttackGetter)item).CommonInstance()!).GetNew();
            ret.DeepCopyIn(
                item,
                errorMask: out errorMask,
                copyMask: copyMask);
            return ret;
        }
        
        public Attack DeepCopy(
            IAttackGetter item,
            ErrorMaskBuilder? errorMask,
            TranslationCrystal? copyMask = null)
        {
            Attack ret = (Attack)((AttackCommon)((IAttackGetter)item).CommonInstance()!).GetNew();
            ret.DeepCopyIn(
                item,
                errorMask: errorMask,
                copyMask: copyMask);
            return ret;
        }
        
    }
    #endregion

}

namespace Mutagen.Bethesda.Skyrim
{
    public partial class Attack
    {
        #region Common Routing
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        ILoquiRegistration ILoquiObject.Registration => Attack_Registration.Instance;
        public static Attack_Registration Registration => Attack_Registration.Instance;
        [DebuggerStepThrough]
        protected object CommonInstance() => AttackCommon.Instance;
        [DebuggerStepThrough]
        protected object CommonSetterInstance()
        {
            return AttackSetterCommon.Instance;
        }
        [DebuggerStepThrough]
        protected object CommonSetterTranslationInstance() => AttackSetterTranslationCommon.Instance;
        [DebuggerStepThrough]
        object IAttackGetter.CommonInstance() => this.CommonInstance();
        [DebuggerStepThrough]
        object IAttackGetter.CommonSetterInstance() => this.CommonSetterInstance();
        [DebuggerStepThrough]
        object IAttackGetter.CommonSetterTranslationInstance() => this.CommonSetterTranslationInstance();

        #endregion

    }
}

#region Modules
#region Xml Translation
namespace Mutagen.Bethesda.Skyrim.Internals
{
    public partial class AttackXmlWriteTranslation : IXmlWriteTranslator
    {
        public readonly static AttackXmlWriteTranslation Instance = new AttackXmlWriteTranslation();

        public static void WriteToNodeXml(
            IAttackGetter item,
            XElement node,
            ErrorMaskBuilder? errorMask,
            TranslationCrystal? translationMask)
        {
            if ((item.AttackData != null)
                && (translationMask?.GetShouldTranslate((int)Attack_FieldIndex.AttackData) ?? true))
            {
                if (item.AttackData.TryGet(out var AttackDataItem))
                {
                    ((AttackDataXmlWriteTranslation)((IXmlItem)AttackDataItem).XmlWriteTranslator).Write(
                        item: AttackDataItem,
                        node: node,
                        name: nameof(item.AttackData),
                        fieldIndex: (int)Attack_FieldIndex.AttackData,
                        errorMask: errorMask,
                        translationMask: translationMask?.GetSubCrystal((int)Attack_FieldIndex.AttackData));
                }
            }
            if ((item.AttackEvent != null)
                && (translationMask?.GetShouldTranslate((int)Attack_FieldIndex.AttackEvent) ?? true))
            {
                StringXmlTranslation.Instance.Write(
                    node: node,
                    name: nameof(item.AttackEvent),
                    item: item.AttackEvent,
                    fieldIndex: (int)Attack_FieldIndex.AttackEvent,
                    errorMask: errorMask);
            }
        }

        public void Write(
            XElement node,
            IAttackGetter item,
            ErrorMaskBuilder? errorMask,
            TranslationCrystal? translationMask,
            string? name = null)
        {
            var elem = new XElement(name ?? "Mutagen.Bethesda.Skyrim.Attack");
            node.Add(elem);
            if (name != null)
            {
                elem.SetAttributeValue("type", "Mutagen.Bethesda.Skyrim.Attack");
            }
            WriteToNodeXml(
                item: item,
                node: elem,
                errorMask: errorMask,
                translationMask: translationMask);
        }

        public void Write(
            XElement node,
            object item,
            ErrorMaskBuilder? errorMask,
            TranslationCrystal? translationMask,
            string? name = null)
        {
            Write(
                item: (IAttackGetter)item,
                name: name,
                node: node,
                errorMask: errorMask,
                translationMask: translationMask);
        }

        public void Write(
            XElement node,
            IAttackGetter item,
            ErrorMaskBuilder? errorMask,
            int fieldIndex,
            TranslationCrystal? translationMask,
            string? name = null)
        {
            errorMask?.PushIndex(fieldIndex);
            try
            {
                Write(
                    item: (IAttackGetter)item,
                    name: name,
                    node: node,
                    errorMask: errorMask,
                    translationMask: translationMask);
            }
            catch (Exception ex)
            when (errorMask != null)
            {
                errorMask.ReportException(ex);
            }
            finally
            {
                errorMask?.PopIndex();
            }
        }

    }

    public partial class AttackXmlCreateTranslation
    {
        public readonly static AttackXmlCreateTranslation Instance = new AttackXmlCreateTranslation();

        public static void FillPublicXml(
            IAttack item,
            XElement node,
            ErrorMaskBuilder? errorMask,
            TranslationCrystal? translationMask)
        {
            try
            {
                foreach (var elem in node.Elements())
                {
                    AttackXmlCreateTranslation.FillPublicElementXml(
                        item: item,
                        node: elem,
                        name: elem.Name.LocalName,
                        errorMask: errorMask,
                        translationMask: translationMask);
                }
            }
            catch (Exception ex)
            when (errorMask != null)
            {
                errorMask.ReportException(ex);
            }
        }

        public static void FillPublicElementXml(
            IAttack item,
            XElement node,
            string name,
            ErrorMaskBuilder? errorMask,
            TranslationCrystal? translationMask)
        {
            switch (name)
            {
                case "AttackData":
                    errorMask?.PushIndex((int)Attack_FieldIndex.AttackData);
                    try
                    {
                        item.AttackData = LoquiXmlTranslation<AttackData>.Instance.Parse(
                            node: node,
                            errorMask: errorMask,
                            translationMask: translationMask?.GetSubCrystal((int)Attack_FieldIndex.AttackData));
                    }
                    catch (Exception ex)
                    when (errorMask != null)
                    {
                        errorMask.ReportException(ex);
                    }
                    finally
                    {
                        errorMask?.PopIndex();
                    }
                    break;
                case "AttackEvent":
                    errorMask?.PushIndex((int)Attack_FieldIndex.AttackEvent);
                    try
                    {
                        item.AttackEvent = StringXmlTranslation.Instance.Parse(
                            node: node,
                            errorMask: errorMask);
                    }
                    catch (Exception ex)
                    when (errorMask != null)
                    {
                        errorMask.ReportException(ex);
                    }
                    finally
                    {
                        errorMask?.PopIndex();
                    }
                    break;
                default:
                    break;
            }
        }

    }

}
namespace Mutagen.Bethesda.Skyrim
{
    #region Xml Write Mixins
    public static class AttackXmlTranslationMixIn
    {
        public static void WriteToXml(
            this IAttackGetter item,
            XElement node,
            out Attack.ErrorMask errorMask,
            Attack.TranslationMask? translationMask = null,
            string? name = null)
        {
            ErrorMaskBuilder errorMaskBuilder = new ErrorMaskBuilder();
            ((AttackXmlWriteTranslation)item.XmlWriteTranslator).Write(
                item: item,
                name: name,
                node: node,
                errorMask: errorMaskBuilder,
                translationMask: translationMask?.GetCrystal());
            errorMask = Attack.ErrorMask.Factory(errorMaskBuilder);
        }

        public static void WriteToXml(
            this IAttackGetter item,
            string path,
            out Attack.ErrorMask errorMask,
            Attack.TranslationMask? translationMask = null,
            string? name = null)
        {
            var node = new XElement("topnode");
            WriteToXml(
                item: item,
                name: name,
                node: node,
                errorMask: out errorMask,
                translationMask: translationMask);
            node.Elements().First().SaveIfChanged(path);
        }

        public static void WriteToXml(
            this IAttackGetter item,
            string path,
            ErrorMaskBuilder? errorMask,
            TranslationCrystal? translationMask = null,
            string? name = null)
        {
            var node = new XElement("topnode");
            WriteToXml(
                item: item,
                name: name,
                node: node,
                errorMask: errorMask,
                translationMask: translationMask);
            node.Elements().First().SaveIfChanged(path);
        }

        public static void WriteToXml(
            this IAttackGetter item,
            Stream stream,
            out Attack.ErrorMask errorMask,
            Attack.TranslationMask? translationMask = null,
            string? name = null)
        {
            var node = new XElement("topnode");
            WriteToXml(
                item: item,
                name: name,
                node: node,
                errorMask: out errorMask,
                translationMask: translationMask);
            node.Elements().First().Save(stream);
        }

        public static void WriteToXml(
            this IAttackGetter item,
            Stream stream,
            ErrorMaskBuilder? errorMask,
            TranslationCrystal? translationMask = null,
            string? name = null)
        {
            var node = new XElement("topnode");
            WriteToXml(
                item: item,
                name: name,
                node: node,
                errorMask: errorMask,
                translationMask: translationMask);
            node.Elements().First().Save(stream);
        }

        public static void WriteToXml(
            this IAttackGetter item,
            XElement node,
            ErrorMaskBuilder? errorMask,
            TranslationCrystal? translationMask = null,
            string? name = null)
        {
            ((AttackXmlWriteTranslation)item.XmlWriteTranslator).Write(
                item: item,
                name: name,
                node: node,
                errorMask: errorMask,
                translationMask: translationMask);
        }

        public static void WriteToXml(
            this IAttackGetter item,
            XElement node,
            string? name = null,
            Attack.TranslationMask? translationMask = null)
        {
            ((AttackXmlWriteTranslation)item.XmlWriteTranslator).Write(
                item: item,
                name: name,
                node: node,
                errorMask: null,
                translationMask: translationMask?.GetCrystal());
        }

        public static void WriteToXml(
            this IAttackGetter item,
            string path,
            string? name = null)
        {
            var node = new XElement("topnode");
            ((AttackXmlWriteTranslation)item.XmlWriteTranslator).Write(
                item: item,
                name: name,
                node: node,
                errorMask: null,
                translationMask: null);
            node.Elements().First().SaveIfChanged(path);
        }

        public static void WriteToXml(
            this IAttackGetter item,
            Stream stream,
            string? name = null)
        {
            var node = new XElement("topnode");
            ((AttackXmlWriteTranslation)item.XmlWriteTranslator).Write(
                item: item,
                name: name,
                node: node,
                errorMask: null,
                translationMask: null);
            node.Elements().First().Save(stream);
        }

    }
    #endregion


}
#endregion

#region Binary Translation
namespace Mutagen.Bethesda.Skyrim.Internals
{
    public partial class AttackBinaryWriteTranslation : IBinaryWriteTranslator
    {
        public readonly static AttackBinaryWriteTranslation Instance = new AttackBinaryWriteTranslation();

        public static void WriteRecordTypes(
            IAttackGetter item,
            MutagenWriter writer,
            RecordTypeConverter? recordTypeConverter)
        {
            if (item.AttackData.TryGet(out var AttackDataItem))
            {
                ((AttackDataBinaryWriteTranslation)((IBinaryItem)AttackDataItem).BinaryWriteTranslator).Write(
                    item: AttackDataItem,
                    writer: writer,
                    recordTypeConverter: recordTypeConverter);
            }
            Mutagen.Bethesda.Binary.StringBinaryTranslation.Instance.WriteNullable(
                writer: writer,
                item: item.AttackEvent,
                header: recordTypeConverter.ConvertToCustom(RecordTypes.ATKE),
                binaryType: StringBinaryType.NullTerminate);
        }

        public void Write(
            MutagenWriter writer,
            IAttackGetter item,
            RecordTypeConverter? recordTypeConverter = null)
        {
            WriteRecordTypes(
                item: item,
                writer: writer,
                recordTypeConverter: recordTypeConverter);
        }

        public void Write(
            MutagenWriter writer,
            object item,
            RecordTypeConverter? recordTypeConverter = null)
        {
            Write(
                item: (IAttackGetter)item,
                writer: writer,
                recordTypeConverter: recordTypeConverter);
        }

    }

    public partial class AttackBinaryCreateTranslation
    {
        public readonly static AttackBinaryCreateTranslation Instance = new AttackBinaryCreateTranslation();

        public static void FillBinaryStructs(
            IAttack item,
            MutagenFrame frame)
        {
        }

        public static ParseResult FillBinaryRecordTypes(
            IAttack item,
            MutagenFrame frame,
            int? lastParsed,
            Dictionary<RecordType, int>? recordParseCount,
            RecordType nextRecordType,
            int contentLength,
            RecordTypeConverter? recordTypeConverter = null)
        {
            nextRecordType = recordTypeConverter.ConvertToStandard(nextRecordType);
            switch (nextRecordType.TypeInt)
            {
                case RecordTypeInts.ATKD:
                {
                    if (lastParsed.HasValue && lastParsed.Value >= (int)Attack_FieldIndex.AttackData) return ParseResult.Stop;
                    item.AttackData = Mutagen.Bethesda.Skyrim.AttackData.CreateFromBinary(frame: frame);
                    return (int)Attack_FieldIndex.AttackData;
                }
                case RecordTypeInts.ATKE:
                {
                    if (lastParsed.HasValue && lastParsed.Value >= (int)Attack_FieldIndex.AttackEvent) return ParseResult.Stop;
                    frame.Position += frame.MetaData.Constants.SubConstants.HeaderLength;
                    item.AttackEvent = Mutagen.Bethesda.Binary.StringBinaryTranslation.Instance.Parse(
                        frame: frame.SpawnWithLength(contentLength),
                        stringBinaryType: StringBinaryType.NullTerminate);
                    return (int)Attack_FieldIndex.AttackEvent;
                }
                default:
                    return ParseResult.Stop;
            }
        }

    }

}
namespace Mutagen.Bethesda.Skyrim
{
    #region Binary Write Mixins
    public static class AttackBinaryTranslationMixIn
    {
        public static void WriteToBinary(
            this IAttackGetter item,
            MutagenWriter writer)
        {
            ((AttackBinaryWriteTranslation)item.BinaryWriteTranslator).Write(
                item: item,
                writer: writer,
                recordTypeConverter: null);
        }

    }
    #endregion


}
namespace Mutagen.Bethesda.Skyrim.Internals
{
    public partial class AttackBinaryOverlay :
        BinaryOverlay,
        IAttackGetter
    {
        #region Common Routing
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        ILoquiRegistration ILoquiObject.Registration => Attack_Registration.Instance;
        public static Attack_Registration Registration => Attack_Registration.Instance;
        [DebuggerStepThrough]
        protected object CommonInstance() => AttackCommon.Instance;
        [DebuggerStepThrough]
        protected object CommonSetterTranslationInstance() => AttackSetterTranslationCommon.Instance;
        [DebuggerStepThrough]
        object IAttackGetter.CommonInstance() => this.CommonInstance();
        [DebuggerStepThrough]
        object? IAttackGetter.CommonSetterInstance() => null;
        [DebuggerStepThrough]
        object IAttackGetter.CommonSetterTranslationInstance() => this.CommonSetterTranslationInstance();

        #endregion

        void IPrintable.ToString(FileGeneration fg, string? name) => this.ToString(fg, name);
        IMask<bool> ILoquiObjectGetter.GetHasBeenSetIMask() => this.GetHasBeenSetMask();
        IMask<bool> IEqualsMask.GetEqualsIMask(object rhs, EqualsMaskHelper.Include include) => this.GetEqualsMask((IAttackGetter)rhs, include);

        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        protected IEnumerable<FormKey> LinkFormKeys => AttackCommon.Instance.GetLinkFormKeys(this);
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        IEnumerable<FormKey> ILinkedFormKeyContainer.LinkFormKeys => AttackCommon.Instance.GetLinkFormKeys(this);
        protected void RemapLinks(IReadOnlyDictionary<FormKey, FormKey> mapping) => AttackCommon.Instance.RemapLinks(this, mapping);
        void ILinkedFormKeyContainer.RemapLinks(IReadOnlyDictionary<FormKey, FormKey> mapping) => AttackCommon.Instance.RemapLinks(this, mapping);
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        protected object XmlWriteTranslator => AttackXmlWriteTranslation.Instance;
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        object IXmlItem.XmlWriteTranslator => this.XmlWriteTranslator;
        void IXmlItem.WriteToXml(
            XElement node,
            ErrorMaskBuilder? errorMask,
            TranslationCrystal? translationMask,
            string? name = null)
        {
            ((AttackXmlWriteTranslation)this.XmlWriteTranslator).Write(
                item: this,
                name: name,
                node: node,
                errorMask: errorMask,
                translationMask: translationMask);
        }
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        protected object BinaryWriteTranslator => AttackBinaryWriteTranslation.Instance;
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        object IBinaryItem.BinaryWriteTranslator => this.BinaryWriteTranslator;
        void IBinaryItem.WriteToBinary(
            MutagenWriter writer,
            RecordTypeConverter? recordTypeConverter = null)
        {
            ((AttackBinaryWriteTranslation)this.BinaryWriteTranslator).Write(
                item: this,
                writer: writer,
                recordTypeConverter: recordTypeConverter);
        }

        #region AttackData
        private RangeInt32? _AttackDataLocation;
        public IAttackDataGetter? AttackData => _AttackDataLocation.HasValue ? AttackDataBinaryOverlay.AttackDataFactory(new OverlayStream(_data.Slice(_AttackDataLocation!.Value.Min), _package), _package) : default;
        public bool AttackData_IsSet => _AttackDataLocation.HasValue;
        #endregion
        #region AttackEvent
        private int? _AttackEventLocation;
        public String? AttackEvent => _AttackEventLocation.HasValue ? BinaryStringUtility.ProcessWholeToZString(HeaderTranslation.ExtractSubrecordMemory(_data, _AttackEventLocation.Value, _package.MetaData.Constants)) : default(string?);
        #endregion
        partial void CustomFactoryEnd(
            OverlayStream stream,
            int finalPos,
            int offset);

        partial void CustomCtor();
        protected AttackBinaryOverlay(
            ReadOnlyMemorySlice<byte> bytes,
            BinaryOverlayFactoryPackage package)
            : base(
                bytes: bytes,
                package: package)
        {
            this.CustomCtor();
        }

        public static AttackBinaryOverlay AttackFactory(
            OverlayStream stream,
            BinaryOverlayFactoryPackage package,
            RecordTypeConverter? recordTypeConverter = null)
        {
            var ret = new AttackBinaryOverlay(
                bytes: stream.RemainingMemory,
                package: package);
            int offset = stream.Position;
            ret.FillTypelessSubrecordTypes(
                stream: stream,
                finalPos: stream.Length,
                offset: offset,
                recordTypeConverter: recordTypeConverter,
                fill: ret.FillRecordType);
            return ret;
        }

        public static AttackBinaryOverlay AttackFactory(
            ReadOnlyMemorySlice<byte> slice,
            BinaryOverlayFactoryPackage package,
            RecordTypeConverter? recordTypeConverter = null)
        {
            return AttackFactory(
                stream: new OverlayStream(slice, package),
                package: package,
                recordTypeConverter: recordTypeConverter);
        }

        public ParseResult FillRecordType(
            OverlayStream stream,
            int finalPos,
            int offset,
            RecordType type,
            int? lastParsed,
            Dictionary<RecordType, int>? recordParseCount,
            RecordTypeConverter? recordTypeConverter = null)
        {
            type = recordTypeConverter.ConvertToStandard(type);
            switch (type.TypeInt)
            {
                case RecordTypeInts.ATKD:
                {
                    if (lastParsed.HasValue && lastParsed.Value >= (int)Attack_FieldIndex.AttackData) return ParseResult.Stop;
                    _AttackDataLocation = new RangeInt32((stream.Position - offset), finalPos);
                    return (int)Attack_FieldIndex.AttackData;
                }
                case RecordTypeInts.ATKE:
                {
                    if (lastParsed.HasValue && lastParsed.Value >= (int)Attack_FieldIndex.AttackEvent) return ParseResult.Stop;
                    _AttackEventLocation = (stream.Position - offset);
                    return (int)Attack_FieldIndex.AttackEvent;
                }
                default:
                    return ParseResult.Stop;
            }
        }
        #region To String

        public void ToString(
            FileGeneration fg,
            string? name = null)
        {
            AttackMixIn.ToString(
                item: this,
                name: name);
        }

        #endregion

    }

}
#endregion

#endregion

