namespace Mutagen.Bethesda.FalloutNV;

public partial class APerkEntryPointEffect
{
    public enum EntryType
    {
        CalculateWeaponDamage = 0,
        CalculateMyCriticalHitChance = 1,
        CalculateMyCriticalHitDamage = 2,
        CalculateMineExplodeChance = 3,
        AdjustLimbDamage = 4,
        AdjustBookSkillPoints = 5,
        ModRecoveredHealth = 6,
        GetShouldAttack = 7,
        ModBuyPrices = 8,
        AddLeveledListOnDeath = 9,
        GetMaxCarryWeight = 10,
        ModAddictionChance = 11,
        ModAddictionDuration = 12,
        ModPositiveChemDuration = 13,
        Activate = 14,
        IgnoreRunningDurationDetection = 15,
        IgnoreBrokenLock = 16,
        ModEnemyCriticalHitChance = 17,
        ModSneakAttackMult = 18,
        ModMaxPlacableMinex = 19,
        ModBowZoom = 20,
        ModRecoverArrowChance = 21,
        ModSkillUse = 22,
        ModTelekinesisDistance = 23,
        ModTelekinesisDamageMult = 24,
        ModTelekinesisDamage = 25,
        ModBashingDamage = 26,
        ModPowerAttackStamina = 27,
        ModPowerAttackDamage = 28,
        ModSpellMagnitude = 29,
        ModSpellDuration = 30,
        ModSecondaryValueWeight = 31,
        ModArmorWeight = 32,
        ModIncomingStagger = 33,
        ModTargetStagger = 34,
        ModAttackDamage = 35,
        ModIncomingDamage = 36,
        ModTargetDamageResistance = 37,
        ModSpellCost = 38,
        ModPercentBlocked = 39,
        ModShieldDefectArrowChance = 40,
        ModIncomingSpellMagnitude = 41,
        ModIncomingSpellDuration = 42,
        ModPlayerIntimidation = 43,
        ModPlayerReputation = 44,
        ModFavorPoints = 45,
        ModBribeAmount = 46,
        ModDetectionLight = 47,
        ModDetectionMovement = 48,
    }
}
